// Generated by Garaga version 1.0.1

use core::circuit::{
    CircuitElement as CE, CircuitInput as CI, CircuitInputs, CircuitModulus, CircuitOutputsTrait,
    EvalCircuitTrait, circuit_add, circuit_inverse, circuit_mul, circuit_sub, u384,
};
use garaga::core::circuit::{AddInputResultTrait2, u288IntoCircuitInputValue};
use garaga::definitions::G1Point;

#[inline(always)]
pub fn run_GRUMPKIN_ZK_HONK_SUMCHECK_SIZE_6_PUB_17_circuit(
    p_public_inputs: Span<u256>,
    p_pairing_point_object: Span<u256>,
    libra_sum: u384,
    sumcheck_univariates_flat: Span<u256>,
    sumcheck_evaluations: Span<u256>,
    libra_evaluation: u384,
    tp_sum_check_u_challenges: Span<u128>,
    tp_gate_challenge: u128,
    tp_eta_1: u384,
    tp_eta_2: u384,
    tp_eta_3: u384,
    tp_beta: u384,
    tp_gamma: u384,
    tp_base_rlc: u384,
    tp_alpha: u128,
    tp_libra_challenge: u384,
    modulus: core::circuit::CircuitModulus,
) -> (u384, u384) {
    // CONSTANT stack
    let in0 = CE::<CI<0>> {}; // 0x1
    let in1 = CE::<CI<1>> {}; // 0x10000000
    let in2 = CE::<CI<2>> {}; // 0x9d80
    let in3 = CE::<CI<3>> {}; // 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593efffec51
    let in4 = CE::<CI<4>> {}; // 0x5a0
    let in5 = CE::<CI<5>> {}; // 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593effffd31
    let in6 = CE::<CI<6>> {}; // 0x240
    let in7 = CE::<CI<7>> {}; // 0x0
    let in8 = CE::<CI<8>> {}; // 0x2
    let in9 = CE::<CI<9>> {}; // 0x3
    let in10 = CE::<CI<10>> {}; // 0x4
    let in11 = CE::<CI<11>> {}; // 0x5
    let in12 = CE::<CI<12>> {}; // 0x6
    let in13 = CE::<CI<13>> {}; // 0x7
    let in14 = CE::<CI<14>> {}; // 0x8
    let in15 = CE::<
        CI<15>,
    > {}; // 0x183227397098d014dc2822db40c0ac2e9419f4243cdcb848a1f0fac9f8000000
    let in16 = CE::<CI<16>> {}; // -0x1 % p
    let in17 = CE::<CI<17>> {}; // 0x11
    let in18 = CE::<CI<18>> {}; // 0x9
    let in19 = CE::<CI<19>> {}; // 0x100000000000000000
    let in20 = CE::<CI<20>> {}; // 0x4000
    let in21 = CE::<
        CI<21>,
    > {}; // 0x10dc6e9c006ea38b04b1e03b4bd9490c0d03f98929ca1d7fb56821fd19d3b6e7
    let in22 = CE::<CI<22>> {}; // 0xc28145b6a44df3e0149b3d0a30b3bb599df9756d4dd9b84a86b38cfb45a740b
    let in23 = CE::<CI<23>> {}; // 0x544b8338791518b2c7645a50392798b21f75bb60e3596170067d00141cac15
    let in24 = CE::<
        CI<24>,
    > {}; // 0x222c01175718386f2e2e82eb122789e352e105a3b8fa852613bc534433ee428b

    // INPUT stack
    let (in25, in26, in27) = (CE::<CI<25>> {}, CE::<CI<26>> {}, CE::<CI<27>> {});
    let (in28, in29, in30) = (CE::<CI<28>> {}, CE::<CI<29>> {}, CE::<CI<30>> {});
    let (in31, in32, in33) = (CE::<CI<31>> {}, CE::<CI<32>> {}, CE::<CI<33>> {});
    let (in34, in35, in36) = (CE::<CI<34>> {}, CE::<CI<35>> {}, CE::<CI<36>> {});
    let (in37, in38, in39) = (CE::<CI<37>> {}, CE::<CI<38>> {}, CE::<CI<39>> {});
    let (in40, in41, in42) = (CE::<CI<40>> {}, CE::<CI<41>> {}, CE::<CI<42>> {});
    let (in43, in44, in45) = (CE::<CI<43>> {}, CE::<CI<44>> {}, CE::<CI<45>> {});
    let (in46, in47, in48) = (CE::<CI<46>> {}, CE::<CI<47>> {}, CE::<CI<48>> {});
    let (in49, in50, in51) = (CE::<CI<49>> {}, CE::<CI<50>> {}, CE::<CI<51>> {});
    let (in52, in53, in54) = (CE::<CI<52>> {}, CE::<CI<53>> {}, CE::<CI<54>> {});
    let (in55, in56, in57) = (CE::<CI<55>> {}, CE::<CI<56>> {}, CE::<CI<57>> {});
    let (in58, in59, in60) = (CE::<CI<58>> {}, CE::<CI<59>> {}, CE::<CI<60>> {});
    let (in61, in62, in63) = (CE::<CI<61>> {}, CE::<CI<62>> {}, CE::<CI<63>> {});
    let (in64, in65, in66) = (CE::<CI<64>> {}, CE::<CI<65>> {}, CE::<CI<66>> {});
    let (in67, in68, in69) = (CE::<CI<67>> {}, CE::<CI<68>> {}, CE::<CI<69>> {});
    let (in70, in71, in72) = (CE::<CI<70>> {}, CE::<CI<71>> {}, CE::<CI<72>> {});
    let (in73, in74, in75) = (CE::<CI<73>> {}, CE::<CI<74>> {}, CE::<CI<75>> {});
    let (in76, in77, in78) = (CE::<CI<76>> {}, CE::<CI<77>> {}, CE::<CI<78>> {});
    let (in79, in80, in81) = (CE::<CI<79>> {}, CE::<CI<80>> {}, CE::<CI<81>> {});
    let (in82, in83, in84) = (CE::<CI<82>> {}, CE::<CI<83>> {}, CE::<CI<84>> {});
    let (in85, in86, in87) = (CE::<CI<85>> {}, CE::<CI<86>> {}, CE::<CI<87>> {});
    let (in88, in89, in90) = (CE::<CI<88>> {}, CE::<CI<89>> {}, CE::<CI<90>> {});
    let (in91, in92, in93) = (CE::<CI<91>> {}, CE::<CI<92>> {}, CE::<CI<93>> {});
    let (in94, in95, in96) = (CE::<CI<94>> {}, CE::<CI<95>> {}, CE::<CI<96>> {});
    let (in97, in98, in99) = (CE::<CI<97>> {}, CE::<CI<98>> {}, CE::<CI<99>> {});
    let (in100, in101, in102) = (CE::<CI<100>> {}, CE::<CI<101>> {}, CE::<CI<102>> {});
    let (in103, in104, in105) = (CE::<CI<103>> {}, CE::<CI<104>> {}, CE::<CI<105>> {});
    let (in106, in107, in108) = (CE::<CI<106>> {}, CE::<CI<107>> {}, CE::<CI<108>> {});
    let (in109, in110, in111) = (CE::<CI<109>> {}, CE::<CI<110>> {}, CE::<CI<111>> {});
    let (in112, in113, in114) = (CE::<CI<112>> {}, CE::<CI<113>> {}, CE::<CI<114>> {});
    let (in115, in116, in117) = (CE::<CI<115>> {}, CE::<CI<116>> {}, CE::<CI<117>> {});
    let (in118, in119, in120) = (CE::<CI<118>> {}, CE::<CI<119>> {}, CE::<CI<120>> {});
    let (in121, in122, in123) = (CE::<CI<121>> {}, CE::<CI<122>> {}, CE::<CI<123>> {});
    let (in124, in125, in126) = (CE::<CI<124>> {}, CE::<CI<125>> {}, CE::<CI<126>> {});
    let (in127, in128, in129) = (CE::<CI<127>> {}, CE::<CI<128>> {}, CE::<CI<129>> {});
    let (in130, in131, in132) = (CE::<CI<130>> {}, CE::<CI<131>> {}, CE::<CI<132>> {});
    let (in133, in134, in135) = (CE::<CI<133>> {}, CE::<CI<134>> {}, CE::<CI<135>> {});
    let (in136, in137, in138) = (CE::<CI<136>> {}, CE::<CI<137>> {}, CE::<CI<138>> {});
    let (in139, in140, in141) = (CE::<CI<139>> {}, CE::<CI<140>> {}, CE::<CI<141>> {});
    let (in142, in143, in144) = (CE::<CI<142>> {}, CE::<CI<143>> {}, CE::<CI<144>> {});
    let (in145, in146, in147) = (CE::<CI<145>> {}, CE::<CI<146>> {}, CE::<CI<147>> {});
    let (in148, in149, in150) = (CE::<CI<148>> {}, CE::<CI<149>> {}, CE::<CI<150>> {});
    let (in151, in152, in153) = (CE::<CI<151>> {}, CE::<CI<152>> {}, CE::<CI<153>> {});
    let t0 = circuit_add(in1, in0);
    let t1 = circuit_mul(in149, t0);
    let t2 = circuit_add(in150, t1);
    let t3 = circuit_add(in0, in0);
    let t4 = circuit_mul(in149, t3);
    let t5 = circuit_sub(in150, t4);
    let t6 = circuit_add(t2, in25);
    let t7 = circuit_mul(in0, t6);
    let t8 = circuit_add(t5, in25);
    let t9 = circuit_mul(in0, t8);
    let t10 = circuit_add(t2, in149);
    let t11 = circuit_sub(t5, in149);
    let t12 = circuit_add(t10, in26);
    let t13 = circuit_mul(t7, t12);
    let t14 = circuit_add(t11, in26);
    let t15 = circuit_mul(t9, t14);
    let t16 = circuit_add(t10, in149);
    let t17 = circuit_sub(t11, in149);
    let t18 = circuit_add(t16, in27);
    let t19 = circuit_mul(t13, t18);
    let t20 = circuit_add(t17, in27);
    let t21 = circuit_mul(t15, t20);
    let t22 = circuit_add(t16, in149);
    let t23 = circuit_sub(t17, in149);
    let t24 = circuit_add(t22, in28);
    let t25 = circuit_mul(t19, t24);
    let t26 = circuit_add(t23, in28);
    let t27 = circuit_mul(t21, t26);
    let t28 = circuit_add(t22, in149);
    let t29 = circuit_sub(t23, in149);
    let t30 = circuit_add(t28, in29);
    let t31 = circuit_mul(t25, t30);
    let t32 = circuit_add(t29, in29);
    let t33 = circuit_mul(t27, t32);
    let t34 = circuit_add(t28, in149);
    let t35 = circuit_sub(t29, in149);
    let t36 = circuit_add(t34, in30);
    let t37 = circuit_mul(t31, t36);
    let t38 = circuit_add(t35, in30);
    let t39 = circuit_mul(t33, t38);
    let t40 = circuit_add(t34, in149);
    let t41 = circuit_sub(t35, in149);
    let t42 = circuit_add(t40, in31);
    let t43 = circuit_mul(t37, t42);
    let t44 = circuit_add(t41, in31);
    let t45 = circuit_mul(t39, t44);
    let t46 = circuit_add(t40, in149);
    let t47 = circuit_sub(t41, in149);
    let t48 = circuit_add(t46, in32);
    let t49 = circuit_mul(t43, t48);
    let t50 = circuit_add(t47, in32);
    let t51 = circuit_mul(t45, t50);
    let t52 = circuit_add(t46, in149);
    let t53 = circuit_sub(t47, in149);
    let t54 = circuit_add(t52, in33);
    let t55 = circuit_mul(t49, t54);
    let t56 = circuit_add(t53, in33);
    let t57 = circuit_mul(t51, t56);
    let t58 = circuit_add(t52, in149);
    let t59 = circuit_sub(t53, in149);
    let t60 = circuit_add(t58, in34);
    let t61 = circuit_mul(t55, t60);
    let t62 = circuit_add(t59, in34);
    let t63 = circuit_mul(t57, t62);
    let t64 = circuit_add(t58, in149);
    let t65 = circuit_sub(t59, in149);
    let t66 = circuit_add(t64, in35);
    let t67 = circuit_mul(t61, t66);
    let t68 = circuit_add(t65, in35);
    let t69 = circuit_mul(t63, t68);
    let t70 = circuit_add(t64, in149);
    let t71 = circuit_sub(t65, in149);
    let t72 = circuit_add(t70, in36);
    let t73 = circuit_mul(t67, t72);
    let t74 = circuit_add(t71, in36);
    let t75 = circuit_mul(t69, t74);
    let t76 = circuit_add(t70, in149);
    let t77 = circuit_sub(t71, in149);
    let t78 = circuit_add(t76, in37);
    let t79 = circuit_mul(t73, t78);
    let t80 = circuit_add(t77, in37);
    let t81 = circuit_mul(t75, t80);
    let t82 = circuit_add(t76, in149);
    let t83 = circuit_sub(t77, in149);
    let t84 = circuit_add(t82, in38);
    let t85 = circuit_mul(t79, t84);
    let t86 = circuit_add(t83, in38);
    let t87 = circuit_mul(t81, t86);
    let t88 = circuit_add(t82, in149);
    let t89 = circuit_sub(t83, in149);
    let t90 = circuit_add(t88, in39);
    let t91 = circuit_mul(t85, t90);
    let t92 = circuit_add(t89, in39);
    let t93 = circuit_mul(t87, t92);
    let t94 = circuit_add(t88, in149);
    let t95 = circuit_sub(t89, in149);
    let t96 = circuit_add(t94, in40);
    let t97 = circuit_mul(t91, t96);
    let t98 = circuit_add(t95, in40);
    let t99 = circuit_mul(t93, t98);
    let t100 = circuit_add(t94, in149);
    let t101 = circuit_sub(t95, in149);
    let t102 = circuit_add(t100, in41);
    let t103 = circuit_mul(t97, t102);
    let t104 = circuit_add(t101, in41);
    let t105 = circuit_mul(t99, t104);
    let t106 = circuit_inverse(t105);
    let t107 = circuit_mul(t103, t106);
    let t108 = circuit_mul(in153, in42);
    let t109 = circuit_add(in43, in44);
    let t110 = circuit_sub(t109, t108);
    let t111 = circuit_mul(t110, in151);
    let t112 = circuit_sub(in139, in7);
    let t113 = circuit_mul(in0, t112);
    let t114 = circuit_sub(in139, in7);
    let t115 = circuit_mul(in2, t114);
    let t116 = circuit_inverse(t115);
    let t117 = circuit_mul(in43, t116);
    let t118 = circuit_add(in7, t117);
    let t119 = circuit_sub(in139, in0);
    let t120 = circuit_mul(t113, t119);
    let t121 = circuit_sub(in139, in0);
    let t122 = circuit_mul(in3, t121);
    let t123 = circuit_inverse(t122);
    let t124 = circuit_mul(in44, t123);
    let t125 = circuit_add(t118, t124);
    let t126 = circuit_sub(in139, in8);
    let t127 = circuit_mul(t120, t126);
    let t128 = circuit_sub(in139, in8);
    let t129 = circuit_mul(in4, t128);
    let t130 = circuit_inverse(t129);
    let t131 = circuit_mul(in45, t130);
    let t132 = circuit_add(t125, t131);
    let t133 = circuit_sub(in139, in9);
    let t134 = circuit_mul(t127, t133);
    let t135 = circuit_sub(in139, in9);
    let t136 = circuit_mul(in5, t135);
    let t137 = circuit_inverse(t136);
    let t138 = circuit_mul(in46, t137);
    let t139 = circuit_add(t132, t138);
    let t140 = circuit_sub(in139, in10);
    let t141 = circuit_mul(t134, t140);
    let t142 = circuit_sub(in139, in10);
    let t143 = circuit_mul(in6, t142);
    let t144 = circuit_inverse(t143);
    let t145 = circuit_mul(in47, t144);
    let t146 = circuit_add(t139, t145);
    let t147 = circuit_sub(in139, in11);
    let t148 = circuit_mul(t141, t147);
    let t149 = circuit_sub(in139, in11);
    let t150 = circuit_mul(in5, t149);
    let t151 = circuit_inverse(t150);
    let t152 = circuit_mul(in48, t151);
    let t153 = circuit_add(t146, t152);
    let t154 = circuit_sub(in139, in12);
    let t155 = circuit_mul(t148, t154);
    let t156 = circuit_sub(in139, in12);
    let t157 = circuit_mul(in4, t156);
    let t158 = circuit_inverse(t157);
    let t159 = circuit_mul(in49, t158);
    let t160 = circuit_add(t153, t159);
    let t161 = circuit_sub(in139, in13);
    let t162 = circuit_mul(t155, t161);
    let t163 = circuit_sub(in139, in13);
    let t164 = circuit_mul(in3, t163);
    let t165 = circuit_inverse(t164);
    let t166 = circuit_mul(in50, t165);
    let t167 = circuit_add(t160, t166);
    let t168 = circuit_sub(in139, in14);
    let t169 = circuit_mul(t162, t168);
    let t170 = circuit_sub(in139, in14);
    let t171 = circuit_mul(in2, t170);
    let t172 = circuit_inverse(t171);
    let t173 = circuit_mul(in51, t172);
    let t174 = circuit_add(t167, t173);
    let t175 = circuit_mul(t174, t169);
    let t176 = circuit_sub(in145, in0);
    let t177 = circuit_mul(in139, t176);
    let t178 = circuit_add(in0, t177);
    let t179 = circuit_mul(in0, t178);
    let t180 = circuit_mul(in151, in151);
    let t181 = circuit_mul(in145, in145);
    let t182 = circuit_add(in52, in53);
    let t183 = circuit_sub(t182, t175);
    let t184 = circuit_mul(t183, t180);
    let t185 = circuit_add(t111, t184);
    let t186 = circuit_sub(in140, in7);
    let t187 = circuit_mul(in0, t186);
    let t188 = circuit_sub(in140, in7);
    let t189 = circuit_mul(in2, t188);
    let t190 = circuit_inverse(t189);
    let t191 = circuit_mul(in52, t190);
    let t192 = circuit_add(in7, t191);
    let t193 = circuit_sub(in140, in0);
    let t194 = circuit_mul(t187, t193);
    let t195 = circuit_sub(in140, in0);
    let t196 = circuit_mul(in3, t195);
    let t197 = circuit_inverse(t196);
    let t198 = circuit_mul(in53, t197);
    let t199 = circuit_add(t192, t198);
    let t200 = circuit_sub(in140, in8);
    let t201 = circuit_mul(t194, t200);
    let t202 = circuit_sub(in140, in8);
    let t203 = circuit_mul(in4, t202);
    let t204 = circuit_inverse(t203);
    let t205 = circuit_mul(in54, t204);
    let t206 = circuit_add(t199, t205);
    let t207 = circuit_sub(in140, in9);
    let t208 = circuit_mul(t201, t207);
    let t209 = circuit_sub(in140, in9);
    let t210 = circuit_mul(in5, t209);
    let t211 = circuit_inverse(t210);
    let t212 = circuit_mul(in55, t211);
    let t213 = circuit_add(t206, t212);
    let t214 = circuit_sub(in140, in10);
    let t215 = circuit_mul(t208, t214);
    let t216 = circuit_sub(in140, in10);
    let t217 = circuit_mul(in6, t216);
    let t218 = circuit_inverse(t217);
    let t219 = circuit_mul(in56, t218);
    let t220 = circuit_add(t213, t219);
    let t221 = circuit_sub(in140, in11);
    let t222 = circuit_mul(t215, t221);
    let t223 = circuit_sub(in140, in11);
    let t224 = circuit_mul(in5, t223);
    let t225 = circuit_inverse(t224);
    let t226 = circuit_mul(in57, t225);
    let t227 = circuit_add(t220, t226);
    let t228 = circuit_sub(in140, in12);
    let t229 = circuit_mul(t222, t228);
    let t230 = circuit_sub(in140, in12);
    let t231 = circuit_mul(in4, t230);
    let t232 = circuit_inverse(t231);
    let t233 = circuit_mul(in58, t232);
    let t234 = circuit_add(t227, t233);
    let t235 = circuit_sub(in140, in13);
    let t236 = circuit_mul(t229, t235);
    let t237 = circuit_sub(in140, in13);
    let t238 = circuit_mul(in3, t237);
    let t239 = circuit_inverse(t238);
    let t240 = circuit_mul(in59, t239);
    let t241 = circuit_add(t234, t240);
    let t242 = circuit_sub(in140, in14);
    let t243 = circuit_mul(t236, t242);
    let t244 = circuit_sub(in140, in14);
    let t245 = circuit_mul(in2, t244);
    let t246 = circuit_inverse(t245);
    let t247 = circuit_mul(in60, t246);
    let t248 = circuit_add(t241, t247);
    let t249 = circuit_mul(t248, t243);
    let t250 = circuit_sub(t181, in0);
    let t251 = circuit_mul(in140, t250);
    let t252 = circuit_add(in0, t251);
    let t253 = circuit_mul(t179, t252);
    let t254 = circuit_mul(t180, in151);
    let t255 = circuit_mul(t181, t181);
    let t256 = circuit_add(in61, in62);
    let t257 = circuit_sub(t256, t249);
    let t258 = circuit_mul(t257, t254);
    let t259 = circuit_add(t185, t258);
    let t260 = circuit_sub(in141, in7);
    let t261 = circuit_mul(in0, t260);
    let t262 = circuit_sub(in141, in7);
    let t263 = circuit_mul(in2, t262);
    let t264 = circuit_inverse(t263);
    let t265 = circuit_mul(in61, t264);
    let t266 = circuit_add(in7, t265);
    let t267 = circuit_sub(in141, in0);
    let t268 = circuit_mul(t261, t267);
    let t269 = circuit_sub(in141, in0);
    let t270 = circuit_mul(in3, t269);
    let t271 = circuit_inverse(t270);
    let t272 = circuit_mul(in62, t271);
    let t273 = circuit_add(t266, t272);
    let t274 = circuit_sub(in141, in8);
    let t275 = circuit_mul(t268, t274);
    let t276 = circuit_sub(in141, in8);
    let t277 = circuit_mul(in4, t276);
    let t278 = circuit_inverse(t277);
    let t279 = circuit_mul(in63, t278);
    let t280 = circuit_add(t273, t279);
    let t281 = circuit_sub(in141, in9);
    let t282 = circuit_mul(t275, t281);
    let t283 = circuit_sub(in141, in9);
    let t284 = circuit_mul(in5, t283);
    let t285 = circuit_inverse(t284);
    let t286 = circuit_mul(in64, t285);
    let t287 = circuit_add(t280, t286);
    let t288 = circuit_sub(in141, in10);
    let t289 = circuit_mul(t282, t288);
    let t290 = circuit_sub(in141, in10);
    let t291 = circuit_mul(in6, t290);
    let t292 = circuit_inverse(t291);
    let t293 = circuit_mul(in65, t292);
    let t294 = circuit_add(t287, t293);
    let t295 = circuit_sub(in141, in11);
    let t296 = circuit_mul(t289, t295);
    let t297 = circuit_sub(in141, in11);
    let t298 = circuit_mul(in5, t297);
    let t299 = circuit_inverse(t298);
    let t300 = circuit_mul(in66, t299);
    let t301 = circuit_add(t294, t300);
    let t302 = circuit_sub(in141, in12);
    let t303 = circuit_mul(t296, t302);
    let t304 = circuit_sub(in141, in12);
    let t305 = circuit_mul(in4, t304);
    let t306 = circuit_inverse(t305);
    let t307 = circuit_mul(in67, t306);
    let t308 = circuit_add(t301, t307);
    let t309 = circuit_sub(in141, in13);
    let t310 = circuit_mul(t303, t309);
    let t311 = circuit_sub(in141, in13);
    let t312 = circuit_mul(in3, t311);
    let t313 = circuit_inverse(t312);
    let t314 = circuit_mul(in68, t313);
    let t315 = circuit_add(t308, t314);
    let t316 = circuit_sub(in141, in14);
    let t317 = circuit_mul(t310, t316);
    let t318 = circuit_sub(in141, in14);
    let t319 = circuit_mul(in2, t318);
    let t320 = circuit_inverse(t319);
    let t321 = circuit_mul(in69, t320);
    let t322 = circuit_add(t315, t321);
    let t323 = circuit_mul(t322, t317);
    let t324 = circuit_sub(t255, in0);
    let t325 = circuit_mul(in141, t324);
    let t326 = circuit_add(in0, t325);
    let t327 = circuit_mul(t253, t326);
    let t328 = circuit_mul(t254, in151);
    let t329 = circuit_mul(t255, t255);
    let t330 = circuit_add(in70, in71);
    let t331 = circuit_sub(t330, t323);
    let t332 = circuit_mul(t331, t328);
    let t333 = circuit_add(t259, t332);
    let t334 = circuit_sub(in142, in7);
    let t335 = circuit_mul(in0, t334);
    let t336 = circuit_sub(in142, in7);
    let t337 = circuit_mul(in2, t336);
    let t338 = circuit_inverse(t337);
    let t339 = circuit_mul(in70, t338);
    let t340 = circuit_add(in7, t339);
    let t341 = circuit_sub(in142, in0);
    let t342 = circuit_mul(t335, t341);
    let t343 = circuit_sub(in142, in0);
    let t344 = circuit_mul(in3, t343);
    let t345 = circuit_inverse(t344);
    let t346 = circuit_mul(in71, t345);
    let t347 = circuit_add(t340, t346);
    let t348 = circuit_sub(in142, in8);
    let t349 = circuit_mul(t342, t348);
    let t350 = circuit_sub(in142, in8);
    let t351 = circuit_mul(in4, t350);
    let t352 = circuit_inverse(t351);
    let t353 = circuit_mul(in72, t352);
    let t354 = circuit_add(t347, t353);
    let t355 = circuit_sub(in142, in9);
    let t356 = circuit_mul(t349, t355);
    let t357 = circuit_sub(in142, in9);
    let t358 = circuit_mul(in5, t357);
    let t359 = circuit_inverse(t358);
    let t360 = circuit_mul(in73, t359);
    let t361 = circuit_add(t354, t360);
    let t362 = circuit_sub(in142, in10);
    let t363 = circuit_mul(t356, t362);
    let t364 = circuit_sub(in142, in10);
    let t365 = circuit_mul(in6, t364);
    let t366 = circuit_inverse(t365);
    let t367 = circuit_mul(in74, t366);
    let t368 = circuit_add(t361, t367);
    let t369 = circuit_sub(in142, in11);
    let t370 = circuit_mul(t363, t369);
    let t371 = circuit_sub(in142, in11);
    let t372 = circuit_mul(in5, t371);
    let t373 = circuit_inverse(t372);
    let t374 = circuit_mul(in75, t373);
    let t375 = circuit_add(t368, t374);
    let t376 = circuit_sub(in142, in12);
    let t377 = circuit_mul(t370, t376);
    let t378 = circuit_sub(in142, in12);
    let t379 = circuit_mul(in4, t378);
    let t380 = circuit_inverse(t379);
    let t381 = circuit_mul(in76, t380);
    let t382 = circuit_add(t375, t381);
    let t383 = circuit_sub(in142, in13);
    let t384 = circuit_mul(t377, t383);
    let t385 = circuit_sub(in142, in13);
    let t386 = circuit_mul(in3, t385);
    let t387 = circuit_inverse(t386);
    let t388 = circuit_mul(in77, t387);
    let t389 = circuit_add(t382, t388);
    let t390 = circuit_sub(in142, in14);
    let t391 = circuit_mul(t384, t390);
    let t392 = circuit_sub(in142, in14);
    let t393 = circuit_mul(in2, t392);
    let t394 = circuit_inverse(t393);
    let t395 = circuit_mul(in78, t394);
    let t396 = circuit_add(t389, t395);
    let t397 = circuit_mul(t396, t391);
    let t398 = circuit_sub(t329, in0);
    let t399 = circuit_mul(in142, t398);
    let t400 = circuit_add(in0, t399);
    let t401 = circuit_mul(t327, t400);
    let t402 = circuit_mul(t328, in151);
    let t403 = circuit_mul(t329, t329);
    let t404 = circuit_add(in79, in80);
    let t405 = circuit_sub(t404, t397);
    let t406 = circuit_mul(t405, t402);
    let t407 = circuit_add(t333, t406);
    let t408 = circuit_sub(in143, in7);
    let t409 = circuit_mul(in0, t408);
    let t410 = circuit_sub(in143, in7);
    let t411 = circuit_mul(in2, t410);
    let t412 = circuit_inverse(t411);
    let t413 = circuit_mul(in79, t412);
    let t414 = circuit_add(in7, t413);
    let t415 = circuit_sub(in143, in0);
    let t416 = circuit_mul(t409, t415);
    let t417 = circuit_sub(in143, in0);
    let t418 = circuit_mul(in3, t417);
    let t419 = circuit_inverse(t418);
    let t420 = circuit_mul(in80, t419);
    let t421 = circuit_add(t414, t420);
    let t422 = circuit_sub(in143, in8);
    let t423 = circuit_mul(t416, t422);
    let t424 = circuit_sub(in143, in8);
    let t425 = circuit_mul(in4, t424);
    let t426 = circuit_inverse(t425);
    let t427 = circuit_mul(in81, t426);
    let t428 = circuit_add(t421, t427);
    let t429 = circuit_sub(in143, in9);
    let t430 = circuit_mul(t423, t429);
    let t431 = circuit_sub(in143, in9);
    let t432 = circuit_mul(in5, t431);
    let t433 = circuit_inverse(t432);
    let t434 = circuit_mul(in82, t433);
    let t435 = circuit_add(t428, t434);
    let t436 = circuit_sub(in143, in10);
    let t437 = circuit_mul(t430, t436);
    let t438 = circuit_sub(in143, in10);
    let t439 = circuit_mul(in6, t438);
    let t440 = circuit_inverse(t439);
    let t441 = circuit_mul(in83, t440);
    let t442 = circuit_add(t435, t441);
    let t443 = circuit_sub(in143, in11);
    let t444 = circuit_mul(t437, t443);
    let t445 = circuit_sub(in143, in11);
    let t446 = circuit_mul(in5, t445);
    let t447 = circuit_inverse(t446);
    let t448 = circuit_mul(in84, t447);
    let t449 = circuit_add(t442, t448);
    let t450 = circuit_sub(in143, in12);
    let t451 = circuit_mul(t444, t450);
    let t452 = circuit_sub(in143, in12);
    let t453 = circuit_mul(in4, t452);
    let t454 = circuit_inverse(t453);
    let t455 = circuit_mul(in85, t454);
    let t456 = circuit_add(t449, t455);
    let t457 = circuit_sub(in143, in13);
    let t458 = circuit_mul(t451, t457);
    let t459 = circuit_sub(in143, in13);
    let t460 = circuit_mul(in3, t459);
    let t461 = circuit_inverse(t460);
    let t462 = circuit_mul(in86, t461);
    let t463 = circuit_add(t456, t462);
    let t464 = circuit_sub(in143, in14);
    let t465 = circuit_mul(t458, t464);
    let t466 = circuit_sub(in143, in14);
    let t467 = circuit_mul(in2, t466);
    let t468 = circuit_inverse(t467);
    let t469 = circuit_mul(in87, t468);
    let t470 = circuit_add(t463, t469);
    let t471 = circuit_mul(t470, t465);
    let t472 = circuit_sub(t403, in0);
    let t473 = circuit_mul(in143, t472);
    let t474 = circuit_add(in0, t473);
    let t475 = circuit_mul(t401, t474);
    let t476 = circuit_mul(t402, in151);
    let t477 = circuit_mul(t403, t403);
    let t478 = circuit_add(in88, in89);
    let t479 = circuit_sub(t478, t471);
    let t480 = circuit_mul(t479, t476);
    let t481 = circuit_add(t407, t480);
    let t482 = circuit_sub(in144, in7);
    let t483 = circuit_mul(in0, t482);
    let t484 = circuit_sub(in144, in7);
    let t485 = circuit_mul(in2, t484);
    let t486 = circuit_inverse(t485);
    let t487 = circuit_mul(in88, t486);
    let t488 = circuit_add(in7, t487);
    let t489 = circuit_sub(in144, in0);
    let t490 = circuit_mul(t483, t489);
    let t491 = circuit_sub(in144, in0);
    let t492 = circuit_mul(in3, t491);
    let t493 = circuit_inverse(t492);
    let t494 = circuit_mul(in89, t493);
    let t495 = circuit_add(t488, t494);
    let t496 = circuit_sub(in144, in8);
    let t497 = circuit_mul(t490, t496);
    let t498 = circuit_sub(in144, in8);
    let t499 = circuit_mul(in4, t498);
    let t500 = circuit_inverse(t499);
    let t501 = circuit_mul(in90, t500);
    let t502 = circuit_add(t495, t501);
    let t503 = circuit_sub(in144, in9);
    let t504 = circuit_mul(t497, t503);
    let t505 = circuit_sub(in144, in9);
    let t506 = circuit_mul(in5, t505);
    let t507 = circuit_inverse(t506);
    let t508 = circuit_mul(in91, t507);
    let t509 = circuit_add(t502, t508);
    let t510 = circuit_sub(in144, in10);
    let t511 = circuit_mul(t504, t510);
    let t512 = circuit_sub(in144, in10);
    let t513 = circuit_mul(in6, t512);
    let t514 = circuit_inverse(t513);
    let t515 = circuit_mul(in92, t514);
    let t516 = circuit_add(t509, t515);
    let t517 = circuit_sub(in144, in11);
    let t518 = circuit_mul(t511, t517);
    let t519 = circuit_sub(in144, in11);
    let t520 = circuit_mul(in5, t519);
    let t521 = circuit_inverse(t520);
    let t522 = circuit_mul(in93, t521);
    let t523 = circuit_add(t516, t522);
    let t524 = circuit_sub(in144, in12);
    let t525 = circuit_mul(t518, t524);
    let t526 = circuit_sub(in144, in12);
    let t527 = circuit_mul(in4, t526);
    let t528 = circuit_inverse(t527);
    let t529 = circuit_mul(in94, t528);
    let t530 = circuit_add(t523, t529);
    let t531 = circuit_sub(in144, in13);
    let t532 = circuit_mul(t525, t531);
    let t533 = circuit_sub(in144, in13);
    let t534 = circuit_mul(in3, t533);
    let t535 = circuit_inverse(t534);
    let t536 = circuit_mul(in95, t535);
    let t537 = circuit_add(t530, t536);
    let t538 = circuit_sub(in144, in14);
    let t539 = circuit_mul(t532, t538);
    let t540 = circuit_sub(in144, in14);
    let t541 = circuit_mul(in2, t540);
    let t542 = circuit_inverse(t541);
    let t543 = circuit_mul(in96, t542);
    let t544 = circuit_add(t537, t543);
    let t545 = circuit_mul(t544, t539);
    let t546 = circuit_sub(t477, in0);
    let t547 = circuit_mul(in144, t546);
    let t548 = circuit_add(in0, t547);
    let t549 = circuit_mul(t475, t548);
    let t550 = circuit_sub(in104, in9);
    let t551 = circuit_mul(t550, in97);
    let t552 = circuit_mul(t551, in126);
    let t553 = circuit_mul(t552, in125);
    let t554 = circuit_mul(t553, in15);
    let t555 = circuit_mul(in99, in125);
    let t556 = circuit_mul(in100, in126);
    let t557 = circuit_mul(in101, in127);
    let t558 = circuit_mul(in102, in128);
    let t559 = circuit_add(t554, t555);
    let t560 = circuit_add(t559, t556);
    let t561 = circuit_add(t560, t557);
    let t562 = circuit_add(t561, t558);
    let t563 = circuit_add(t562, in98);
    let t564 = circuit_sub(in104, in0);
    let t565 = circuit_mul(t564, in136);
    let t566 = circuit_add(t563, t565);
    let t567 = circuit_mul(t566, in104);
    let t568 = circuit_mul(t567, t549);
    let t569 = circuit_add(in125, in128);
    let t570 = circuit_add(t569, in97);
    let t571 = circuit_sub(t570, in133);
    let t572 = circuit_sub(in104, in8);
    let t573 = circuit_mul(t571, t572);
    let t574 = circuit_sub(in104, in0);
    let t575 = circuit_mul(t573, t574);
    let t576 = circuit_mul(t575, in104);
    let t577 = circuit_mul(t576, t549);
    let t578 = circuit_mul(in115, in149);
    let t579 = circuit_add(in125, t578);
    let t580 = circuit_add(t579, in150);
    let t581 = circuit_mul(in116, in149);
    let t582 = circuit_add(in126, t581);
    let t583 = circuit_add(t582, in150);
    let t584 = circuit_mul(t580, t583);
    let t585 = circuit_mul(in117, in149);
    let t586 = circuit_add(in127, t585);
    let t587 = circuit_add(t586, in150);
    let t588 = circuit_mul(t584, t587);
    let t589 = circuit_mul(in118, in149);
    let t590 = circuit_add(in128, t589);
    let t591 = circuit_add(t590, in150);
    let t592 = circuit_mul(t588, t591);
    let t593 = circuit_mul(in111, in149);
    let t594 = circuit_add(in125, t593);
    let t595 = circuit_add(t594, in150);
    let t596 = circuit_mul(in112, in149);
    let t597 = circuit_add(in126, t596);
    let t598 = circuit_add(t597, in150);
    let t599 = circuit_mul(t595, t598);
    let t600 = circuit_mul(in113, in149);
    let t601 = circuit_add(in127, t600);
    let t602 = circuit_add(t601, in150);
    let t603 = circuit_mul(t599, t602);
    let t604 = circuit_mul(in114, in149);
    let t605 = circuit_add(in128, t604);
    let t606 = circuit_add(t605, in150);
    let t607 = circuit_mul(t603, t606);
    let t608 = circuit_add(in129, in123);
    let t609 = circuit_mul(t592, t608);
    let t610 = circuit_mul(in124, t107);
    let t611 = circuit_add(in137, t610);
    let t612 = circuit_mul(t607, t611);
    let t613 = circuit_sub(t609, t612);
    let t614 = circuit_mul(t613, t549);
    let t615 = circuit_mul(in124, in137);
    let t616 = circuit_mul(t615, t549);
    let t617 = circuit_mul(in120, in146);
    let t618 = circuit_mul(in121, in147);
    let t619 = circuit_mul(in122, in148);
    let t620 = circuit_add(in119, in150);
    let t621 = circuit_add(t620, t617);
    let t622 = circuit_add(t621, t618);
    let t623 = circuit_add(t622, t619);
    let t624 = circuit_mul(in100, in133);
    let t625 = circuit_add(in125, in150);
    let t626 = circuit_add(t625, t624);
    let t627 = circuit_mul(in97, in134);
    let t628 = circuit_add(in126, t627);
    let t629 = circuit_mul(in98, in135);
    let t630 = circuit_add(in127, t629);
    let t631 = circuit_mul(t628, in146);
    let t632 = circuit_mul(t630, in147);
    let t633 = circuit_mul(in101, in148);
    let t634 = circuit_add(t626, t631);
    let t635 = circuit_add(t634, t632);
    let t636 = circuit_add(t635, t633);
    let t637 = circuit_mul(in130, t623);
    let t638 = circuit_mul(in130, t636);
    let t639 = circuit_add(in132, in103);
    let t640 = circuit_mul(in132, in103);
    let t641 = circuit_sub(t639, t640);
    let t642 = circuit_mul(t636, t623);
    let t643 = circuit_mul(t642, in130);
    let t644 = circuit_sub(t643, t641);
    let t645 = circuit_mul(t644, t549);
    let t646 = circuit_mul(in103, t637);
    let t647 = circuit_mul(in131, t638);
    let t648 = circuit_sub(t646, t647);
    let t649 = circuit_mul(in132, in132);
    let t650 = circuit_sub(t649, in132);
    let t651 = circuit_mul(t650, t549);
    let t652 = circuit_mul(in105, t549);
    let t653 = circuit_sub(in126, in125);
    let t654 = circuit_sub(in127, in126);
    let t655 = circuit_sub(in128, in127);
    let t656 = circuit_sub(in133, in128);
    let t657 = circuit_add(t653, in16);
    let t658 = circuit_add(t657, in16);
    let t659 = circuit_add(t658, in16);
    let t660 = circuit_mul(t653, t657);
    let t661 = circuit_mul(t660, t658);
    let t662 = circuit_mul(t661, t659);
    let t663 = circuit_mul(t662, t652);
    let t664 = circuit_add(t654, in16);
    let t665 = circuit_add(t664, in16);
    let t666 = circuit_add(t665, in16);
    let t667 = circuit_mul(t654, t664);
    let t668 = circuit_mul(t667, t665);
    let t669 = circuit_mul(t668, t666);
    let t670 = circuit_mul(t669, t652);
    let t671 = circuit_add(t655, in16);
    let t672 = circuit_add(t671, in16);
    let t673 = circuit_add(t672, in16);
    let t674 = circuit_mul(t655, t671);
    let t675 = circuit_mul(t674, t672);
    let t676 = circuit_mul(t675, t673);
    let t677 = circuit_mul(t676, t652);
    let t678 = circuit_add(t656, in16);
    let t679 = circuit_add(t678, in16);
    let t680 = circuit_add(t679, in16);
    let t681 = circuit_mul(t656, t678);
    let t682 = circuit_mul(t681, t679);
    let t683 = circuit_mul(t682, t680);
    let t684 = circuit_mul(t683, t652);
    let t685 = circuit_sub(in133, in126);
    let t686 = circuit_mul(in127, in127);
    let t687 = circuit_mul(in136, in136);
    let t688 = circuit_mul(in127, in136);
    let t689 = circuit_mul(t688, in99);
    let t690 = circuit_add(in134, in133);
    let t691 = circuit_add(t690, in126);
    let t692 = circuit_mul(t691, t685);
    let t693 = circuit_mul(t692, t685);
    let t694 = circuit_sub(t693, t687);
    let t695 = circuit_sub(t694, t686);
    let t696 = circuit_add(t695, t689);
    let t697 = circuit_add(t696, t689);
    let t698 = circuit_sub(in0, in97);
    let t699 = circuit_mul(t697, t549);
    let t700 = circuit_mul(t699, in106);
    let t701 = circuit_mul(t700, t698);
    let t702 = circuit_add(in127, in135);
    let t703 = circuit_mul(in136, in99);
    let t704 = circuit_sub(t703, in127);
    let t705 = circuit_mul(t702, t685);
    let t706 = circuit_sub(in134, in126);
    let t707 = circuit_mul(t706, t704);
    let t708 = circuit_add(t705, t707);
    let t709 = circuit_mul(t708, t549);
    let t710 = circuit_mul(t709, in106);
    let t711 = circuit_mul(t710, t698);
    let t712 = circuit_add(t686, in17);
    let t713 = circuit_mul(t712, in126);
    let t714 = circuit_add(t686, t686);
    let t715 = circuit_add(t714, t714);
    let t716 = circuit_mul(t713, in18);
    let t717 = circuit_add(in134, in126);
    let t718 = circuit_add(t717, in126);
    let t719 = circuit_mul(t718, t715);
    let t720 = circuit_sub(t719, t716);
    let t721 = circuit_mul(t720, t549);
    let t722 = circuit_mul(t721, in106);
    let t723 = circuit_mul(t722, in97);
    let t724 = circuit_add(t701, t723);
    let t725 = circuit_add(in126, in126);
    let t726 = circuit_add(t725, in126);
    let t727 = circuit_mul(t726, in126);
    let t728 = circuit_sub(in126, in134);
    let t729 = circuit_mul(t727, t728);
    let t730 = circuit_add(in127, in127);
    let t731 = circuit_add(in127, in135);
    let t732 = circuit_mul(t730, t731);
    let t733 = circuit_sub(t729, t732);
    let t734 = circuit_mul(t733, t549);
    let t735 = circuit_mul(t734, in106);
    let t736 = circuit_mul(t735, in97);
    let t737 = circuit_add(t711, t736);
    let t738 = circuit_mul(in127, in148);
    let t739 = circuit_mul(in126, in147);
    let t740 = circuit_add(t738, t739);
    let t741 = circuit_mul(in125, in146);
    let t742 = circuit_add(t740, t741);
    let t743 = circuit_add(t742, in98);
    let t744 = circuit_sub(t743, in128);
    let t745 = circuit_sub(in133, in125);
    let t746 = circuit_sub(in136, in128);
    let t747 = circuit_sub(t745, in0);
    let t748 = circuit_mul(t745, t747);
    let t749 = circuit_mul(t745, in16);
    let t750 = circuit_add(t749, in0);
    let t751 = circuit_mul(t750, t746);
    let t752 = circuit_mul(in99, in100);
    let t753 = circuit_mul(in107, t549);
    let t754 = circuit_mul(t752, t753);
    let t755 = circuit_mul(t751, t754);
    let t756 = circuit_mul(t748, t754);
    let t757 = circuit_mul(t744, t752);
    let t758 = circuit_sub(in128, t743);
    let t759 = circuit_sub(t758, in0);
    let t760 = circuit_mul(t758, t759);
    let t761 = circuit_mul(in135, in148);
    let t762 = circuit_mul(in134, in147);
    let t763 = circuit_mul(in133, in146);
    let t764 = circuit_add(t761, t762);
    let t765 = circuit_add(t764, t763);
    let t766 = circuit_sub(in136, t765);
    let t767 = circuit_sub(in135, in127);
    let t768 = circuit_mul(t745, in16);
    let t769 = circuit_add(t768, in0);
    let t770 = circuit_mul(t766, in16);
    let t771 = circuit_add(t770, in0);
    let t772 = circuit_mul(t769, t767);
    let t773 = circuit_mul(t772, t771);
    let t774 = circuit_mul(t766, t766);
    let t775 = circuit_sub(t774, t766);
    let t776 = circuit_mul(in101, t753);
    let t777 = circuit_mul(t773, t776);
    let t778 = circuit_mul(t748, t776);
    let t779 = circuit_mul(t775, t776);
    let t780 = circuit_mul(t760, in101);
    let t781 = circuit_sub(in134, in126);
    let t782 = circuit_mul(t745, in16);
    let t783 = circuit_add(t782, in0);
    let t784 = circuit_mul(t783, t781);
    let t785 = circuit_sub(t784, in127);
    let t786 = circuit_mul(in102, in99);
    let t787 = circuit_mul(t785, t786);
    let t788 = circuit_mul(in97, in99);
    let t789 = circuit_mul(t744, t788);
    let t790 = circuit_add(t757, t787);
    let t791 = circuit_add(t790, t789);
    let t792 = circuit_add(t791, t780);
    let t793 = circuit_mul(t792, t753);
    let t794 = circuit_mul(in125, in134);
    let t795 = circuit_mul(in133, in126);
    let t796 = circuit_add(t794, t795);
    let t797 = circuit_mul(in125, in128);
    let t798 = circuit_mul(in126, in127);
    let t799 = circuit_add(t797, t798);
    let t800 = circuit_sub(t799, in135);
    let t801 = circuit_mul(t800, in19);
    let t802 = circuit_sub(t801, in136);
    let t803 = circuit_add(t802, t796);
    let t804 = circuit_mul(t803, in102);
    let t805 = circuit_mul(t796, in19);
    let t806 = circuit_mul(in133, in134);
    let t807 = circuit_add(t805, t806);
    let t808 = circuit_add(in127, in128);
    let t809 = circuit_sub(t807, t808);
    let t810 = circuit_mul(t809, in101);
    let t811 = circuit_add(t807, in128);
    let t812 = circuit_add(in135, in136);
    let t813 = circuit_sub(t811, t812);
    let t814 = circuit_mul(t813, in97);
    let t815 = circuit_add(t810, t804);
    let t816 = circuit_add(t815, t814);
    let t817 = circuit_mul(t816, in100);
    let t818 = circuit_mul(in134, in20);
    let t819 = circuit_add(t818, in133);
    let t820 = circuit_mul(t819, in20);
    let t821 = circuit_add(t820, in127);
    let t822 = circuit_mul(t821, in20);
    let t823 = circuit_add(t822, in126);
    let t824 = circuit_mul(t823, in20);
    let t825 = circuit_add(t824, in125);
    let t826 = circuit_sub(t825, in128);
    let t827 = circuit_mul(t826, in102);
    let t828 = circuit_mul(in135, in20);
    let t829 = circuit_add(t828, in134);
    let t830 = circuit_mul(t829, in20);
    let t831 = circuit_add(t830, in133);
    let t832 = circuit_mul(t831, in20);
    let t833 = circuit_add(t832, in128);
    let t834 = circuit_mul(t833, in20);
    let t835 = circuit_add(t834, in127);
    let t836 = circuit_sub(t835, in136);
    let t837 = circuit_mul(t836, in97);
    let t838 = circuit_add(t827, t837);
    let t839 = circuit_mul(t838, in101);
    let t840 = circuit_add(t817, t839);
    let t841 = circuit_mul(t840, in108);
    let t842 = circuit_mul(t841, t549);
    let t843 = circuit_add(in125, in99);
    let t844 = circuit_add(in126, in100);
    let t845 = circuit_add(in127, in101);
    let t846 = circuit_add(in128, in102);
    let t847 = circuit_mul(t843, t843);
    let t848 = circuit_mul(t847, t847);
    let t849 = circuit_mul(t848, t843);
    let t850 = circuit_mul(t844, t844);
    let t851 = circuit_mul(t850, t850);
    let t852 = circuit_mul(t851, t844);
    let t853 = circuit_mul(t845, t845);
    let t854 = circuit_mul(t853, t853);
    let t855 = circuit_mul(t854, t845);
    let t856 = circuit_mul(t846, t846);
    let t857 = circuit_mul(t856, t856);
    let t858 = circuit_mul(t857, t846);
    let t859 = circuit_add(t849, t852);
    let t860 = circuit_add(t855, t858);
    let t861 = circuit_add(t852, t852);
    let t862 = circuit_add(t861, t860);
    let t863 = circuit_add(t858, t858);
    let t864 = circuit_add(t863, t859);
    let t865 = circuit_add(t860, t860);
    let t866 = circuit_add(t865, t865);
    let t867 = circuit_add(t866, t864);
    let t868 = circuit_add(t859, t859);
    let t869 = circuit_add(t868, t868);
    let t870 = circuit_add(t869, t862);
    let t871 = circuit_add(t864, t870);
    let t872 = circuit_add(t862, t867);
    let t873 = circuit_mul(in109, t549);
    let t874 = circuit_sub(t871, in133);
    let t875 = circuit_mul(t873, t874);
    let t876 = circuit_sub(t870, in134);
    let t877 = circuit_mul(t873, t876);
    let t878 = circuit_sub(t872, in135);
    let t879 = circuit_mul(t873, t878);
    let t880 = circuit_sub(t867, in136);
    let t881 = circuit_mul(t873, t880);
    let t882 = circuit_add(in125, in99);
    let t883 = circuit_mul(t882, t882);
    let t884 = circuit_mul(t883, t883);
    let t885 = circuit_mul(t884, t882);
    let t886 = circuit_add(t885, in126);
    let t887 = circuit_add(t886, in127);
    let t888 = circuit_add(t887, in128);
    let t889 = circuit_mul(in110, t549);
    let t890 = circuit_mul(t885, in21);
    let t891 = circuit_add(t890, t888);
    let t892 = circuit_sub(t891, in133);
    let t893 = circuit_mul(t889, t892);
    let t894 = circuit_mul(in126, in22);
    let t895 = circuit_add(t894, t888);
    let t896 = circuit_sub(t895, in134);
    let t897 = circuit_mul(t889, t896);
    let t898 = circuit_mul(in127, in23);
    let t899 = circuit_add(t898, t888);
    let t900 = circuit_sub(t899, in135);
    let t901 = circuit_mul(t889, t900);
    let t902 = circuit_mul(in128, in24);
    let t903 = circuit_add(t902, t888);
    let t904 = circuit_sub(t903, in136);
    let t905 = circuit_mul(t889, t904);
    let t906 = circuit_mul(t577, in152);
    let t907 = circuit_add(t568, t906);
    let t908 = circuit_mul(in152, in152);
    let t909 = circuit_mul(t614, t908);
    let t910 = circuit_add(t907, t909);
    let t911 = circuit_mul(t908, in152);
    let t912 = circuit_mul(t616, t911);
    let t913 = circuit_add(t910, t912);
    let t914 = circuit_mul(t911, in152);
    let t915 = circuit_mul(t645, t914);
    let t916 = circuit_add(t913, t915);
    let t917 = circuit_mul(t914, in152);
    let t918 = circuit_mul(t648, t917);
    let t919 = circuit_add(t916, t918);
    let t920 = circuit_mul(t917, in152);
    let t921 = circuit_mul(t651, t920);
    let t922 = circuit_add(t919, t921);
    let t923 = circuit_mul(t920, in152);
    let t924 = circuit_mul(t663, t923);
    let t925 = circuit_add(t922, t924);
    let t926 = circuit_mul(t923, in152);
    let t927 = circuit_mul(t670, t926);
    let t928 = circuit_add(t925, t927);
    let t929 = circuit_mul(t926, in152);
    let t930 = circuit_mul(t677, t929);
    let t931 = circuit_add(t928, t930);
    let t932 = circuit_mul(t929, in152);
    let t933 = circuit_mul(t684, t932);
    let t934 = circuit_add(t931, t933);
    let t935 = circuit_mul(t932, in152);
    let t936 = circuit_mul(t724, t935);
    let t937 = circuit_add(t934, t936);
    let t938 = circuit_mul(t935, in152);
    let t939 = circuit_mul(t737, t938);
    let t940 = circuit_add(t937, t939);
    let t941 = circuit_mul(t938, in152);
    let t942 = circuit_mul(t793, t941);
    let t943 = circuit_add(t940, t942);
    let t944 = circuit_mul(t941, in152);
    let t945 = circuit_mul(t755, t944);
    let t946 = circuit_add(t943, t945);
    let t947 = circuit_mul(t944, in152);
    let t948 = circuit_mul(t756, t947);
    let t949 = circuit_add(t946, t948);
    let t950 = circuit_mul(t947, in152);
    let t951 = circuit_mul(t777, t950);
    let t952 = circuit_add(t949, t951);
    let t953 = circuit_mul(t950, in152);
    let t954 = circuit_mul(t778, t953);
    let t955 = circuit_add(t952, t954);
    let t956 = circuit_mul(t953, in152);
    let t957 = circuit_mul(t779, t956);
    let t958 = circuit_add(t955, t957);
    let t959 = circuit_mul(t956, in152);
    let t960 = circuit_mul(t842, t959);
    let t961 = circuit_add(t958, t960);
    let t962 = circuit_mul(t959, in152);
    let t963 = circuit_mul(t875, t962);
    let t964 = circuit_add(t961, t963);
    let t965 = circuit_mul(t962, in152);
    let t966 = circuit_mul(t877, t965);
    let t967 = circuit_add(t964, t966);
    let t968 = circuit_mul(t965, in152);
    let t969 = circuit_mul(t879, t968);
    let t970 = circuit_add(t967, t969);
    let t971 = circuit_mul(t968, in152);
    let t972 = circuit_mul(t881, t971);
    let t973 = circuit_add(t970, t972);
    let t974 = circuit_mul(t971, in152);
    let t975 = circuit_mul(t893, t974);
    let t976 = circuit_add(t973, t975);
    let t977 = circuit_mul(t974, in152);
    let t978 = circuit_mul(t897, t977);
    let t979 = circuit_add(t976, t978);
    let t980 = circuit_mul(t977, in152);
    let t981 = circuit_mul(t901, t980);
    let t982 = circuit_add(t979, t981);
    let t983 = circuit_mul(t980, in152);
    let t984 = circuit_mul(t905, t983);
    let t985 = circuit_add(t982, t984);
    let t986 = circuit_mul(in141, in142);
    let t987 = circuit_mul(t986, in143);
    let t988 = circuit_mul(t987, in144);
    let t989 = circuit_sub(in0, t988);
    let t990 = circuit_mul(t985, t989);
    let t991 = circuit_mul(in138, in153);
    let t992 = circuit_add(t990, t991);
    let t993 = circuit_sub(t992, t545);

    let modulus = modulus;

    let mut circuit_inputs = (t481, t993).new_inputs();
    // Prefill constants:

    circuit_inputs = circuit_inputs
        .next_span(ZK_HONK_SUMCHECK_SIZE_6_PUB_17_GRUMPKIN_CONSTANTS.span()); // in0 - in24

    // Fill inputs:

    for val in p_public_inputs {
        circuit_inputs = circuit_inputs.next_u256(*val);
    } // in25 - in25

    for val in p_pairing_point_object {
        circuit_inputs = circuit_inputs.next_u256(*val);
    } // in26 - in41

    circuit_inputs = circuit_inputs.next_2(libra_sum); // in42

    for val in sumcheck_univariates_flat {
        circuit_inputs = circuit_inputs.next_u256(*val);
    } // in43 - in96

    for val in sumcheck_evaluations {
        circuit_inputs = circuit_inputs.next_u256(*val);
    } // in97 - in137

    circuit_inputs = circuit_inputs.next_2(libra_evaluation); // in138

    for val in tp_sum_check_u_challenges {
        circuit_inputs = circuit_inputs.next_u128(*val);
    } // in139 - in144

    circuit_inputs = circuit_inputs.next_u128(tp_gate_challenge); // in145
    circuit_inputs = circuit_inputs.next_2(tp_eta_1); // in146
    circuit_inputs = circuit_inputs.next_2(tp_eta_2); // in147
    circuit_inputs = circuit_inputs.next_2(tp_eta_3); // in148
    circuit_inputs = circuit_inputs.next_2(tp_beta); // in149
    circuit_inputs = circuit_inputs.next_2(tp_gamma); // in150
    circuit_inputs = circuit_inputs.next_2(tp_base_rlc); // in151
    circuit_inputs = circuit_inputs.next_u128(tp_alpha); // in152
    circuit_inputs = circuit_inputs.next_2(tp_libra_challenge); // in153

    let outputs = circuit_inputs.done_2().eval(modulus).unwrap();
    let check_rlc: u384 = outputs.get_output(t481);
    let check: u384 = outputs.get_output(t993);
    return (check_rlc, check);
}
const ZK_HONK_SUMCHECK_SIZE_6_PUB_17_GRUMPKIN_CONSTANTS: [u384; 25] = [
    u384 { limb0: 0x1, limb1: 0x0, limb2: 0x0, limb3: 0x0 },
    u384 { limb0: 0x10000000, limb1: 0x0, limb2: 0x0, limb3: 0x0 },
    u384 { limb0: 0x9d80, limb1: 0x0, limb2: 0x0, limb3: 0x0 },
    u384 {
        limb0: 0x79b9709143e1f593efffec51,
        limb1: 0xb85045b68181585d2833e848,
        limb2: 0x30644e72e131a029,
        limb3: 0x0,
    },
    u384 { limb0: 0x5a0, limb1: 0x0, limb2: 0x0, limb3: 0x0 },
    u384 {
        limb0: 0x79b9709143e1f593effffd31,
        limb1: 0xb85045b68181585d2833e848,
        limb2: 0x30644e72e131a029,
        limb3: 0x0,
    },
    u384 { limb0: 0x240, limb1: 0x0, limb2: 0x0, limb3: 0x0 },
    u384 { limb0: 0x0, limb1: 0x0, limb2: 0x0, limb3: 0x0 },
    u384 { limb0: 0x2, limb1: 0x0, limb2: 0x0, limb3: 0x0 },
    u384 { limb0: 0x3, limb1: 0x0, limb2: 0x0, limb3: 0x0 },
    u384 { limb0: 0x4, limb1: 0x0, limb2: 0x0, limb3: 0x0 },
    u384 { limb0: 0x5, limb1: 0x0, limb2: 0x0, limb3: 0x0 },
    u384 { limb0: 0x6, limb1: 0x0, limb2: 0x0, limb3: 0x0 },
    u384 { limb0: 0x7, limb1: 0x0, limb2: 0x0, limb3: 0x0 },
    u384 { limb0: 0x8, limb1: 0x0, limb2: 0x0, limb3: 0x0 },
    u384 {
        limb0: 0x3cdcb848a1f0fac9f8000000,
        limb1: 0xdc2822db40c0ac2e9419f424,
        limb2: 0x183227397098d014,
        limb3: 0x0,
    },
    u384 {
        limb0: 0x79b9709143e1f593f0000000,
        limb1: 0xb85045b68181585d2833e848,
        limb2: 0x30644e72e131a029,
        limb3: 0x0,
    },
    u384 { limb0: 0x11, limb1: 0x0, limb2: 0x0, limb3: 0x0 },
    u384 { limb0: 0x9, limb1: 0x0, limb2: 0x0, limb3: 0x0 },
    u384 { limb0: 0x100000000000000000, limb1: 0x0, limb2: 0x0, limb3: 0x0 },
    u384 { limb0: 0x4000, limb1: 0x0, limb2: 0x0, limb3: 0x0 },
    u384 {
        limb0: 0x29ca1d7fb56821fd19d3b6e7,
        limb1: 0x4b1e03b4bd9490c0d03f989,
        limb2: 0x10dc6e9c006ea38b,
        limb3: 0x0,
    },
    u384 {
        limb0: 0xd4dd9b84a86b38cfb45a740b,
        limb1: 0x149b3d0a30b3bb599df9756,
        limb2: 0xc28145b6a44df3e,
        limb3: 0x0,
    },
    u384 {
        limb0: 0x60e3596170067d00141cac15,
        limb1: 0xb2c7645a50392798b21f75bb,
        limb2: 0x544b8338791518,
        limb3: 0x0,
    },
    u384 {
        limb0: 0xb8fa852613bc534433ee428b,
        limb1: 0x2e2e82eb122789e352e105a3,
        limb2: 0x222c01175718386f,
        limb3: 0x0,
    },
];
#[inline(always)]
pub fn run_GRUMPKIN_ZKHONK_PREP_MSM_SCALARS_SIZE_6_circuit(
    p_sumcheck_evaluations: Span<u256>,
    p_gemini_masking_eval: u384,
    p_gemini_a_evaluations: Span<u256>,
    p_libra_poly_evals: Span<u256>,
    tp_gemini_r: u384,
    tp_rho: u384,
    tp_shplonk_z: u384,
    tp_shplonk_nu: u384,
    tp_sum_check_u_challenges: Span<u128>,
    modulus: core::circuit::CircuitModulus,
) -> (
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
    u384,
) {
    // CONSTANT stack
    let in0 = CE::<CI<0>> {}; // 0x0
    let in1 = CE::<CI<1>> {}; // 0x1
    let in2 = CE::<CI<2>> {}; // 0x7b0c561a6148404f086204a9f36ffb0617942546750f230c893619174a57a76

    // INPUT stack
    let (in3, in4, in5) = (CE::<CI<3>> {}, CE::<CI<4>> {}, CE::<CI<5>> {});
    let (in6, in7, in8) = (CE::<CI<6>> {}, CE::<CI<7>> {}, CE::<CI<8>> {});
    let (in9, in10, in11) = (CE::<CI<9>> {}, CE::<CI<10>> {}, CE::<CI<11>> {});
    let (in12, in13, in14) = (CE::<CI<12>> {}, CE::<CI<13>> {}, CE::<CI<14>> {});
    let (in15, in16, in17) = (CE::<CI<15>> {}, CE::<CI<16>> {}, CE::<CI<17>> {});
    let (in18, in19, in20) = (CE::<CI<18>> {}, CE::<CI<19>> {}, CE::<CI<20>> {});
    let (in21, in22, in23) = (CE::<CI<21>> {}, CE::<CI<22>> {}, CE::<CI<23>> {});
    let (in24, in25, in26) = (CE::<CI<24>> {}, CE::<CI<25>> {}, CE::<CI<26>> {});
    let (in27, in28, in29) = (CE::<CI<27>> {}, CE::<CI<28>> {}, CE::<CI<29>> {});
    let (in30, in31, in32) = (CE::<CI<30>> {}, CE::<CI<31>> {}, CE::<CI<32>> {});
    let (in33, in34, in35) = (CE::<CI<33>> {}, CE::<CI<34>> {}, CE::<CI<35>> {});
    let (in36, in37, in38) = (CE::<CI<36>> {}, CE::<CI<37>> {}, CE::<CI<38>> {});
    let (in39, in40, in41) = (CE::<CI<39>> {}, CE::<CI<40>> {}, CE::<CI<41>> {});
    let (in42, in43, in44) = (CE::<CI<42>> {}, CE::<CI<43>> {}, CE::<CI<44>> {});
    let (in45, in46, in47) = (CE::<CI<45>> {}, CE::<CI<46>> {}, CE::<CI<47>> {});
    let (in48, in49, in50) = (CE::<CI<48>> {}, CE::<CI<49>> {}, CE::<CI<50>> {});
    let (in51, in52, in53) = (CE::<CI<51>> {}, CE::<CI<52>> {}, CE::<CI<53>> {});
    let (in54, in55, in56) = (CE::<CI<54>> {}, CE::<CI<55>> {}, CE::<CI<56>> {});
    let (in57, in58, in59) = (CE::<CI<57>> {}, CE::<CI<58>> {}, CE::<CI<59>> {});
    let (in60, in61, in62) = (CE::<CI<60>> {}, CE::<CI<61>> {}, CE::<CI<62>> {});
    let (in63, in64) = (CE::<CI<63>> {}, CE::<CI<64>> {});
    let t0 = circuit_mul(in55, in55);
    let t1 = circuit_mul(t0, t0);
    let t2 = circuit_mul(t1, t1);
    let t3 = circuit_mul(t2, t2);
    let t4 = circuit_mul(t3, t3);
    let t5 = circuit_sub(in57, in55);
    let t6 = circuit_inverse(t5);
    let t7 = circuit_add(in57, in55);
    let t8 = circuit_inverse(t7);
    let t9 = circuit_mul(in58, t8);
    let t10 = circuit_add(t6, t9);
    let t11 = circuit_inverse(in55);
    let t12 = circuit_mul(in58, t8);
    let t13 = circuit_sub(t6, t12);
    let t14 = circuit_mul(t11, t13);
    let t15 = circuit_sub(in0, t14);
    let t16 = circuit_sub(in0, t10);
    let t17 = circuit_mul(t16, in56);
    let t18 = circuit_mul(in3, in56);
    let t19 = circuit_add(in44, t18);
    let t20 = circuit_mul(in56, in56);
    let t21 = circuit_mul(t16, t20);
    let t22 = circuit_mul(in4, t20);
    let t23 = circuit_add(t19, t22);
    let t24 = circuit_mul(t20, in56);
    let t25 = circuit_mul(t16, t24);
    let t26 = circuit_mul(in5, t24);
    let t27 = circuit_add(t23, t26);
    let t28 = circuit_mul(t24, in56);
    let t29 = circuit_mul(t16, t28);
    let t30 = circuit_mul(in6, t28);
    let t31 = circuit_add(t27, t30);
    let t32 = circuit_mul(t28, in56);
    let t33 = circuit_mul(t16, t32);
    let t34 = circuit_mul(in7, t32);
    let t35 = circuit_add(t31, t34);
    let t36 = circuit_mul(t32, in56);
    let t37 = circuit_mul(t16, t36);
    let t38 = circuit_mul(in8, t36);
    let t39 = circuit_add(t35, t38);
    let t40 = circuit_mul(t36, in56);
    let t41 = circuit_mul(t16, t40);
    let t42 = circuit_mul(in9, t40);
    let t43 = circuit_add(t39, t42);
    let t44 = circuit_mul(t40, in56);
    let t45 = circuit_mul(t16, t44);
    let t46 = circuit_mul(in10, t44);
    let t47 = circuit_add(t43, t46);
    let t48 = circuit_mul(t44, in56);
    let t49 = circuit_mul(t16, t48);
    let t50 = circuit_mul(in11, t48);
    let t51 = circuit_add(t47, t50);
    let t52 = circuit_mul(t48, in56);
    let t53 = circuit_mul(t16, t52);
    let t54 = circuit_mul(in12, t52);
    let t55 = circuit_add(t51, t54);
    let t56 = circuit_mul(t52, in56);
    let t57 = circuit_mul(t16, t56);
    let t58 = circuit_mul(in13, t56);
    let t59 = circuit_add(t55, t58);
    let t60 = circuit_mul(t56, in56);
    let t61 = circuit_mul(t16, t60);
    let t62 = circuit_mul(in14, t60);
    let t63 = circuit_add(t59, t62);
    let t64 = circuit_mul(t60, in56);
    let t65 = circuit_mul(t16, t64);
    let t66 = circuit_mul(in15, t64);
    let t67 = circuit_add(t63, t66);
    let t68 = circuit_mul(t64, in56);
    let t69 = circuit_mul(t16, t68);
    let t70 = circuit_mul(in16, t68);
    let t71 = circuit_add(t67, t70);
    let t72 = circuit_mul(t68, in56);
    let t73 = circuit_mul(t16, t72);
    let t74 = circuit_mul(in17, t72);
    let t75 = circuit_add(t71, t74);
    let t76 = circuit_mul(t72, in56);
    let t77 = circuit_mul(t16, t76);
    let t78 = circuit_mul(in18, t76);
    let t79 = circuit_add(t75, t78);
    let t80 = circuit_mul(t76, in56);
    let t81 = circuit_mul(t16, t80);
    let t82 = circuit_mul(in19, t80);
    let t83 = circuit_add(t79, t82);
    let t84 = circuit_mul(t80, in56);
    let t85 = circuit_mul(t16, t84);
    let t86 = circuit_mul(in20, t84);
    let t87 = circuit_add(t83, t86);
    let t88 = circuit_mul(t84, in56);
    let t89 = circuit_mul(t16, t88);
    let t90 = circuit_mul(in21, t88);
    let t91 = circuit_add(t87, t90);
    let t92 = circuit_mul(t88, in56);
    let t93 = circuit_mul(t16, t92);
    let t94 = circuit_mul(in22, t92);
    let t95 = circuit_add(t91, t94);
    let t96 = circuit_mul(t92, in56);
    let t97 = circuit_mul(t16, t96);
    let t98 = circuit_mul(in23, t96);
    let t99 = circuit_add(t95, t98);
    let t100 = circuit_mul(t96, in56);
    let t101 = circuit_mul(t16, t100);
    let t102 = circuit_mul(in24, t100);
    let t103 = circuit_add(t99, t102);
    let t104 = circuit_mul(t100, in56);
    let t105 = circuit_mul(t16, t104);
    let t106 = circuit_mul(in25, t104);
    let t107 = circuit_add(t103, t106);
    let t108 = circuit_mul(t104, in56);
    let t109 = circuit_mul(t16, t108);
    let t110 = circuit_mul(in26, t108);
    let t111 = circuit_add(t107, t110);
    let t112 = circuit_mul(t108, in56);
    let t113 = circuit_mul(t16, t112);
    let t114 = circuit_mul(in27, t112);
    let t115 = circuit_add(t111, t114);
    let t116 = circuit_mul(t112, in56);
    let t117 = circuit_mul(t16, t116);
    let t118 = circuit_mul(in28, t116);
    let t119 = circuit_add(t115, t118);
    let t120 = circuit_mul(t116, in56);
    let t121 = circuit_mul(t16, t120);
    let t122 = circuit_mul(in29, t120);
    let t123 = circuit_add(t119, t122);
    let t124 = circuit_mul(t120, in56);
    let t125 = circuit_mul(t16, t124);
    let t126 = circuit_mul(in30, t124);
    let t127 = circuit_add(t123, t126);
    let t128 = circuit_mul(t124, in56);
    let t129 = circuit_mul(t16, t128);
    let t130 = circuit_mul(in31, t128);
    let t131 = circuit_add(t127, t130);
    let t132 = circuit_mul(t128, in56);
    let t133 = circuit_mul(t16, t132);
    let t134 = circuit_mul(in32, t132);
    let t135 = circuit_add(t131, t134);
    let t136 = circuit_mul(t132, in56);
    let t137 = circuit_mul(t16, t136);
    let t138 = circuit_mul(in33, t136);
    let t139 = circuit_add(t135, t138);
    let t140 = circuit_mul(t136, in56);
    let t141 = circuit_mul(t16, t140);
    let t142 = circuit_mul(in34, t140);
    let t143 = circuit_add(t139, t142);
    let t144 = circuit_mul(t140, in56);
    let t145 = circuit_mul(t16, t144);
    let t146 = circuit_mul(in35, t144);
    let t147 = circuit_add(t143, t146);
    let t148 = circuit_mul(t144, in56);
    let t149 = circuit_mul(t16, t148);
    let t150 = circuit_mul(in36, t148);
    let t151 = circuit_add(t147, t150);
    let t152 = circuit_mul(t148, in56);
    let t153 = circuit_mul(t16, t152);
    let t154 = circuit_mul(in37, t152);
    let t155 = circuit_add(t151, t154);
    let t156 = circuit_mul(t152, in56);
    let t157 = circuit_mul(t16, t156);
    let t158 = circuit_mul(in38, t156);
    let t159 = circuit_add(t155, t158);
    let t160 = circuit_mul(t156, in56);
    let t161 = circuit_mul(t15, t160);
    let t162 = circuit_add(t129, t161);
    let t163 = circuit_mul(in39, t160);
    let t164 = circuit_add(t159, t163);
    let t165 = circuit_mul(t160, in56);
    let t166 = circuit_mul(t15, t165);
    let t167 = circuit_add(t133, t166);
    let t168 = circuit_mul(in40, t165);
    let t169 = circuit_add(t164, t168);
    let t170 = circuit_mul(t165, in56);
    let t171 = circuit_mul(t15, t170);
    let t172 = circuit_add(t137, t171);
    let t173 = circuit_mul(in41, t170);
    let t174 = circuit_add(t169, t173);
    let t175 = circuit_mul(t170, in56);
    let t176 = circuit_mul(t15, t175);
    let t177 = circuit_add(t141, t176);
    let t178 = circuit_mul(in42, t175);
    let t179 = circuit_add(t174, t178);
    let t180 = circuit_mul(t175, in56);
    let t181 = circuit_mul(t15, t180);
    let t182 = circuit_add(t145, t181);
    let t183 = circuit_mul(in43, t180);
    let t184 = circuit_add(t179, t183);
    let t185 = circuit_sub(in1, in64);
    let t186 = circuit_mul(t4, t185);
    let t187 = circuit_mul(t4, t184);
    let t188 = circuit_add(t187, t187);
    let t189 = circuit_sub(t186, in64);
    let t190 = circuit_mul(in50, t189);
    let t191 = circuit_sub(t188, t190);
    let t192 = circuit_add(t186, in64);
    let t193 = circuit_inverse(t192);
    let t194 = circuit_mul(t191, t193);
    let t195 = circuit_sub(in1, in63);
    let t196 = circuit_mul(t3, t195);
    let t197 = circuit_mul(t3, t194);
    let t198 = circuit_add(t197, t197);
    let t199 = circuit_sub(t196, in63);
    let t200 = circuit_mul(in49, t199);
    let t201 = circuit_sub(t198, t200);
    let t202 = circuit_add(t196, in63);
    let t203 = circuit_inverse(t202);
    let t204 = circuit_mul(t201, t203);
    let t205 = circuit_sub(in1, in62);
    let t206 = circuit_mul(t2, t205);
    let t207 = circuit_mul(t2, t204);
    let t208 = circuit_add(t207, t207);
    let t209 = circuit_sub(t206, in62);
    let t210 = circuit_mul(in48, t209);
    let t211 = circuit_sub(t208, t210);
    let t212 = circuit_add(t206, in62);
    let t213 = circuit_inverse(t212);
    let t214 = circuit_mul(t211, t213);
    let t215 = circuit_sub(in1, in61);
    let t216 = circuit_mul(t1, t215);
    let t217 = circuit_mul(t1, t214);
    let t218 = circuit_add(t217, t217);
    let t219 = circuit_sub(t216, in61);
    let t220 = circuit_mul(in47, t219);
    let t221 = circuit_sub(t218, t220);
    let t222 = circuit_add(t216, in61);
    let t223 = circuit_inverse(t222);
    let t224 = circuit_mul(t221, t223);
    let t225 = circuit_sub(in1, in60);
    let t226 = circuit_mul(t0, t225);
    let t227 = circuit_mul(t0, t224);
    let t228 = circuit_add(t227, t227);
    let t229 = circuit_sub(t226, in60);
    let t230 = circuit_mul(in46, t229);
    let t231 = circuit_sub(t228, t230);
    let t232 = circuit_add(t226, in60);
    let t233 = circuit_inverse(t232);
    let t234 = circuit_mul(t231, t233);
    let t235 = circuit_sub(in1, in59);
    let t236 = circuit_mul(in55, t235);
    let t237 = circuit_mul(in55, t234);
    let t238 = circuit_add(t237, t237);
    let t239 = circuit_sub(t236, in59);
    let t240 = circuit_mul(in45, t239);
    let t241 = circuit_sub(t238, t240);
    let t242 = circuit_add(t236, in59);
    let t243 = circuit_inverse(t242);
    let t244 = circuit_mul(t241, t243);
    let t245 = circuit_mul(t244, t6);
    let t246 = circuit_mul(in45, in58);
    let t247 = circuit_mul(t246, t8);
    let t248 = circuit_add(t245, t247);
    let t249 = circuit_mul(in58, in58);
    let t250 = circuit_sub(in57, t0);
    let t251 = circuit_inverse(t250);
    let t252 = circuit_add(in57, t0);
    let t253 = circuit_inverse(t252);
    let t254 = circuit_mul(t249, t251);
    let t255 = circuit_mul(in58, t253);
    let t256 = circuit_mul(t249, t255);
    let t257 = circuit_add(t256, t254);
    let t258 = circuit_sub(in0, t257);
    let t259 = circuit_mul(t256, in46);
    let t260 = circuit_mul(t254, t234);
    let t261 = circuit_add(t259, t260);
    let t262 = circuit_add(t248, t261);
    let t263 = circuit_mul(in58, in58);
    let t264 = circuit_mul(t249, t263);
    let t265 = circuit_sub(in57, t1);
    let t266 = circuit_inverse(t265);
    let t267 = circuit_add(in57, t1);
    let t268 = circuit_inverse(t267);
    let t269 = circuit_mul(t264, t266);
    let t270 = circuit_mul(in58, t268);
    let t271 = circuit_mul(t264, t270);
    let t272 = circuit_add(t271, t269);
    let t273 = circuit_sub(in0, t272);
    let t274 = circuit_mul(t271, in47);
    let t275 = circuit_mul(t269, t224);
    let t276 = circuit_add(t274, t275);
    let t277 = circuit_add(t262, t276);
    let t278 = circuit_mul(in58, in58);
    let t279 = circuit_mul(t264, t278);
    let t280 = circuit_sub(in57, t2);
    let t281 = circuit_inverse(t280);
    let t282 = circuit_add(in57, t2);
    let t283 = circuit_inverse(t282);
    let t284 = circuit_mul(t279, t281);
    let t285 = circuit_mul(in58, t283);
    let t286 = circuit_mul(t279, t285);
    let t287 = circuit_add(t286, t284);
    let t288 = circuit_sub(in0, t287);
    let t289 = circuit_mul(t286, in48);
    let t290 = circuit_mul(t284, t214);
    let t291 = circuit_add(t289, t290);
    let t292 = circuit_add(t277, t291);
    let t293 = circuit_mul(in58, in58);
    let t294 = circuit_mul(t279, t293);
    let t295 = circuit_sub(in57, t3);
    let t296 = circuit_inverse(t295);
    let t297 = circuit_add(in57, t3);
    let t298 = circuit_inverse(t297);
    let t299 = circuit_mul(t294, t296);
    let t300 = circuit_mul(in58, t298);
    let t301 = circuit_mul(t294, t300);
    let t302 = circuit_add(t301, t299);
    let t303 = circuit_sub(in0, t302);
    let t304 = circuit_mul(t301, in49);
    let t305 = circuit_mul(t299, t204);
    let t306 = circuit_add(t304, t305);
    let t307 = circuit_add(t292, t306);
    let t308 = circuit_mul(in58, in58);
    let t309 = circuit_mul(t294, t308);
    let t310 = circuit_sub(in57, t4);
    let t311 = circuit_inverse(t310);
    let t312 = circuit_add(in57, t4);
    let t313 = circuit_inverse(t312);
    let t314 = circuit_mul(t309, t311);
    let t315 = circuit_mul(in58, t313);
    let t316 = circuit_mul(t309, t315);
    let t317 = circuit_add(t316, t314);
    let t318 = circuit_sub(in0, t317);
    let t319 = circuit_mul(t316, in50);
    let t320 = circuit_mul(t314, t194);
    let t321 = circuit_add(t319, t320);
    let t322 = circuit_add(t307, t321);
    let t323 = circuit_mul(in58, in58);
    let t324 = circuit_mul(t309, t323);
    let t325 = circuit_sub(in57, in55);
    let t326 = circuit_inverse(t325);
    let t327 = circuit_mul(in2, in55);
    let t328 = circuit_sub(in57, t327);
    let t329 = circuit_inverse(t328);
    let t330 = circuit_mul(in58, in58);
    let t331 = circuit_mul(t324, t330);
    let t332 = circuit_mul(t326, t331);
    let t333 = circuit_sub(in0, t332);
    let t334 = circuit_mul(t331, in58);
    let t335 = circuit_mul(t332, in51);
    let t336 = circuit_add(t322, t335);
    let t337 = circuit_mul(t329, t334);
    let t338 = circuit_sub(in0, t337);
    let t339 = circuit_mul(t334, in58);
    let t340 = circuit_mul(t337, in52);
    let t341 = circuit_add(t336, t340);
    let t342 = circuit_mul(t326, t339);
    let t343 = circuit_sub(in0, t342);
    let t344 = circuit_mul(t339, in58);
    let t345 = circuit_mul(t342, in53);
    let t346 = circuit_add(t341, t345);
    let t347 = circuit_mul(t326, t344);
    let t348 = circuit_sub(in0, t347);
    let t349 = circuit_mul(t347, in54);
    let t350 = circuit_add(t346, t349);
    let t351 = circuit_add(t338, t343);

    let modulus = modulus;

    let mut circuit_inputs = (
        t16,
        t17,
        t21,
        t25,
        t29,
        t33,
        t37,
        t41,
        t45,
        t49,
        t53,
        t57,
        t61,
        t65,
        t69,
        t73,
        t77,
        t81,
        t85,
        t89,
        t93,
        t97,
        t101,
        t105,
        t109,
        t113,
        t117,
        t121,
        t125,
        t162,
        t167,
        t172,
        t177,
        t182,
        t149,
        t153,
        t157,
        t258,
        t273,
        t288,
        t303,
        t318,
        t333,
        t351,
        t348,
        t350,
    )
        .new_inputs();
    // Prefill constants:
    circuit_inputs = circuit_inputs.next_2([0x0, 0x0, 0x0, 0x0]); // in0
    circuit_inputs = circuit_inputs.next_2([0x1, 0x0, 0x0, 0x0]); // in1
    circuit_inputs = circuit_inputs
        .next_2(
            [0x6750f230c893619174a57a76, 0xf086204a9f36ffb061794254, 0x7b0c561a6148404, 0x0],
        ); // in2
    // Fill inputs:

    for val in p_sumcheck_evaluations {
        circuit_inputs = circuit_inputs.next_u256(*val);
    } // in3 - in43

    circuit_inputs = circuit_inputs.next_2(p_gemini_masking_eval); // in44

    for val in p_gemini_a_evaluations {
        circuit_inputs = circuit_inputs.next_u256(*val);
    } // in45 - in50

    for val in p_libra_poly_evals {
        circuit_inputs = circuit_inputs.next_u256(*val);
    } // in51 - in54

    circuit_inputs = circuit_inputs.next_2(tp_gemini_r); // in55
    circuit_inputs = circuit_inputs.next_2(tp_rho); // in56
    circuit_inputs = circuit_inputs.next_2(tp_shplonk_z); // in57
    circuit_inputs = circuit_inputs.next_2(tp_shplonk_nu); // in58

    for val in tp_sum_check_u_challenges {
        circuit_inputs = circuit_inputs.next_u128(*val);
    } // in59 - in64

    let outputs = circuit_inputs.done_2().eval(modulus).unwrap();
    let scalar_1: u384 = outputs.get_output(t16);
    let scalar_2: u384 = outputs.get_output(t17);
    let scalar_3: u384 = outputs.get_output(t21);
    let scalar_4: u384 = outputs.get_output(t25);
    let scalar_5: u384 = outputs.get_output(t29);
    let scalar_6: u384 = outputs.get_output(t33);
    let scalar_7: u384 = outputs.get_output(t37);
    let scalar_8: u384 = outputs.get_output(t41);
    let scalar_9: u384 = outputs.get_output(t45);
    let scalar_10: u384 = outputs.get_output(t49);
    let scalar_11: u384 = outputs.get_output(t53);
    let scalar_12: u384 = outputs.get_output(t57);
    let scalar_13: u384 = outputs.get_output(t61);
    let scalar_14: u384 = outputs.get_output(t65);
    let scalar_15: u384 = outputs.get_output(t69);
    let scalar_16: u384 = outputs.get_output(t73);
    let scalar_17: u384 = outputs.get_output(t77);
    let scalar_18: u384 = outputs.get_output(t81);
    let scalar_19: u384 = outputs.get_output(t85);
    let scalar_20: u384 = outputs.get_output(t89);
    let scalar_21: u384 = outputs.get_output(t93);
    let scalar_22: u384 = outputs.get_output(t97);
    let scalar_23: u384 = outputs.get_output(t101);
    let scalar_24: u384 = outputs.get_output(t105);
    let scalar_25: u384 = outputs.get_output(t109);
    let scalar_26: u384 = outputs.get_output(t113);
    let scalar_27: u384 = outputs.get_output(t117);
    let scalar_28: u384 = outputs.get_output(t121);
    let scalar_29: u384 = outputs.get_output(t125);
    let scalar_30: u384 = outputs.get_output(t162);
    let scalar_31: u384 = outputs.get_output(t167);
    let scalar_32: u384 = outputs.get_output(t172);
    let scalar_33: u384 = outputs.get_output(t177);
    let scalar_34: u384 = outputs.get_output(t182);
    let scalar_35: u384 = outputs.get_output(t149);
    let scalar_36: u384 = outputs.get_output(t153);
    let scalar_37: u384 = outputs.get_output(t157);
    let scalar_38: u384 = outputs.get_output(t258);
    let scalar_39: u384 = outputs.get_output(t273);
    let scalar_40: u384 = outputs.get_output(t288);
    let scalar_41: u384 = outputs.get_output(t303);
    let scalar_42: u384 = outputs.get_output(t318);
    let scalar_43: u384 = outputs.get_output(t333);
    let scalar_44: u384 = outputs.get_output(t351);
    let scalar_45: u384 = outputs.get_output(t348);
    let scalar_46: u384 = outputs.get_output(t350);
    return (
        scalar_1,
        scalar_2,
        scalar_3,
        scalar_4,
        scalar_5,
        scalar_6,
        scalar_7,
        scalar_8,
        scalar_9,
        scalar_10,
        scalar_11,
        scalar_12,
        scalar_13,
        scalar_14,
        scalar_15,
        scalar_16,
        scalar_17,
        scalar_18,
        scalar_19,
        scalar_20,
        scalar_21,
        scalar_22,
        scalar_23,
        scalar_24,
        scalar_25,
        scalar_26,
        scalar_27,
        scalar_28,
        scalar_29,
        scalar_30,
        scalar_31,
        scalar_32,
        scalar_33,
        scalar_34,
        scalar_35,
        scalar_36,
        scalar_37,
        scalar_38,
        scalar_39,
        scalar_40,
        scalar_41,
        scalar_42,
        scalar_43,
        scalar_44,
        scalar_45,
        scalar_46,
    );
}
#[inline(always)]
pub fn run_GRUMPKIN_ZK_HONK_EVALS_CONS_INIT_SIZE_6_circuit(
    tp_gemini_r: u384, modulus: core::circuit::CircuitModulus,
) -> (u384, u384) {
    // CONSTANT stack
    let in0 = CE::<CI<0>> {}; // 0x1
    let in1 = CE::<CI<1>> {}; // 0x204bd3277422fad364751ad938e2b5e6a54cf8c68712848a692c553d0329f5d6

    // INPUT stack
    let in2 = CE::<CI<2>> {};
    let t0 = circuit_sub(in2, in0);
    let t1 = circuit_inverse(t0);
    let t2 = circuit_mul(in1, in2);

    let modulus = modulus;

    let mut circuit_inputs = (t1, t2).new_inputs();
    // Prefill constants:
    circuit_inputs = circuit_inputs.next_2([0x1, 0x0, 0x0, 0x0]); // in0
    circuit_inputs = circuit_inputs
        .next_2(
            [0x8712848a692c553d0329f5d6, 0x64751ad938e2b5e6a54cf8c6, 0x204bd3277422fad3, 0x0],
        ); // in1
    // Fill inputs:
    circuit_inputs = circuit_inputs.next_2(tp_gemini_r); // in2

    let outputs = circuit_inputs.done_2().eval(modulus).unwrap();
    let challenge_poly_eval: u384 = outputs.get_output(t1);
    let root_power_times_tp_gemini_r: u384 = outputs.get_output(t2);
    return (challenge_poly_eval, root_power_times_tp_gemini_r);
}
#[inline(always)]
pub fn run_GRUMPKIN_ZK_HONK_EVALS_CONS_LOOP_SIZE_6_circuit(
    challenge_poly_eval: u384,
    root_power_times_tp_gemini_r: u384,
    tp_sumcheck_u_challenge: u384,
    modulus: core::circuit::CircuitModulus,
) -> (u384, u384) {
    // CONSTANT stack
    let in0 = CE::<CI<0>> {}; // 0x1
    let in1 = CE::<CI<1>> {}; // 0x204bd3277422fad364751ad938e2b5e6a54cf8c68712848a692c553d0329f5d6

    // INPUT stack
    let (in2, in3, in4) = (CE::<CI<2>> {}, CE::<CI<3>> {}, CE::<CI<4>> {});
    let t0 = circuit_sub(in3, in0);
    let t1 = circuit_inverse(t0);
    let t2 = circuit_mul(in0, t1);
    let t3 = circuit_add(in2, t2);
    let t4 = circuit_mul(in3, in1);
    let t5 = circuit_mul(in0, in4);
    let t6 = circuit_sub(t4, in0);
    let t7 = circuit_inverse(t6);
    let t8 = circuit_mul(t5, t7);
    let t9 = circuit_add(t3, t8);
    let t10 = circuit_mul(t4, in1);
    let t11 = circuit_mul(t5, in4);
    let t12 = circuit_sub(t10, in0);
    let t13 = circuit_inverse(t12);
    let t14 = circuit_mul(t11, t13);
    let t15 = circuit_add(t9, t14);
    let t16 = circuit_mul(t10, in1);
    let t17 = circuit_mul(t11, in4);
    let t18 = circuit_sub(t16, in0);
    let t19 = circuit_inverse(t18);
    let t20 = circuit_mul(t17, t19);
    let t21 = circuit_add(t15, t20);
    let t22 = circuit_mul(t16, in1);
    let t23 = circuit_mul(t17, in4);
    let t24 = circuit_sub(t22, in0);
    let t25 = circuit_inverse(t24);
    let t26 = circuit_mul(t23, t25);
    let t27 = circuit_add(t21, t26);
    let t28 = circuit_mul(t22, in1);
    let t29 = circuit_mul(t23, in4);
    let t30 = circuit_sub(t28, in0);
    let t31 = circuit_inverse(t30);
    let t32 = circuit_mul(t29, t31);
    let t33 = circuit_add(t27, t32);
    let t34 = circuit_mul(t28, in1);
    let t35 = circuit_mul(t29, in4);
    let t36 = circuit_sub(t34, in0);
    let t37 = circuit_inverse(t36);
    let t38 = circuit_mul(t35, t37);
    let t39 = circuit_add(t33, t38);
    let t40 = circuit_mul(t34, in1);
    let t41 = circuit_mul(t35, in4);
    let t42 = circuit_sub(t40, in0);
    let t43 = circuit_inverse(t42);
    let t44 = circuit_mul(t41, t43);
    let t45 = circuit_add(t39, t44);
    let t46 = circuit_mul(t40, in1);
    let t47 = circuit_mul(t41, in4);
    let t48 = circuit_sub(t46, in0);
    let t49 = circuit_inverse(t48);
    let t50 = circuit_mul(t47, t49);
    let t51 = circuit_add(t45, t50);
    let t52 = circuit_mul(t46, in1);

    let modulus = modulus;

    let mut circuit_inputs = (t51, t52).new_inputs();
    // Prefill constants:
    circuit_inputs = circuit_inputs.next_2([0x1, 0x0, 0x0, 0x0]); // in0
    circuit_inputs = circuit_inputs
        .next_2(
            [0x8712848a692c553d0329f5d6, 0x64751ad938e2b5e6a54cf8c6, 0x204bd3277422fad3, 0x0],
        ); // in1
    // Fill inputs:
    circuit_inputs = circuit_inputs.next_2(challenge_poly_eval); // in2
    circuit_inputs = circuit_inputs.next_2(root_power_times_tp_gemini_r); // in3
    circuit_inputs = circuit_inputs.next_2(tp_sumcheck_u_challenge); // in4

    let outputs = circuit_inputs.done_2().eval(modulus).unwrap();
    let challenge_poly_eval: u384 = outputs.get_output(t51);
    let root_power_times_tp_gemini_r: u384 = outputs.get_output(t52);
    return (challenge_poly_eval, root_power_times_tp_gemini_r);
}
#[inline(always)]
pub fn run_GRUMPKIN_ZK_HONK_EVALS_CONS_DONE_SIZE_6_circuit(
    p_libra_evaluation: u384,
    p_libra_poly_evals: Span<u256>,
    tp_gemini_r: u384,
    challenge_poly_eval: u384,
    root_power_times_tp_gemini_r: u384,
    modulus: core::circuit::CircuitModulus,
) -> (u384, u384) {
    // CONSTANT stack
    let in0 = CE::<CI<0>> {}; // 0x204bd3277422fad364751ad938e2b5e6a54cf8c68712848a692c553d0329f5d6
    let in1 = CE::<CI<1>> {}; // 0x1
    let in2 = CE::<CI<2>> {}; // 0x3033ea246e506e898e97f570caffd704cb0bb460313fb720b29e139e5c100001

    // INPUT stack
    let (in3, in4, in5) = (CE::<CI<3>> {}, CE::<CI<4>> {}, CE::<CI<5>> {});
    let (in6, in7, in8) = (CE::<CI<6>> {}, CE::<CI<7>> {}, CE::<CI<8>> {});
    let (in9, in10) = (CE::<CI<9>> {}, CE::<CI<10>> {});
    let t0 = circuit_mul(in10, in0);
    let t1 = circuit_mul(t0, in0);
    let t2 = circuit_mul(t1, in0);
    let t3 = circuit_mul(t2, in0);
    let t4 = circuit_mul(t3, in0);
    let t5 = circuit_mul(t4, in0);
    let t6 = circuit_mul(t5, in0);
    let t7 = circuit_mul(t6, in0);
    let t8 = circuit_mul(t7, in0);
    let t9 = circuit_mul(t8, in0);
    let t10 = circuit_mul(t9, in0);
    let t11 = circuit_mul(t10, in0);
    let t12 = circuit_mul(t11, in0);
    let t13 = circuit_mul(t12, in0);
    let t14 = circuit_mul(t13, in0);
    let t15 = circuit_mul(t14, in0);
    let t16 = circuit_mul(t15, in0);
    let t17 = circuit_mul(t16, in0);
    let t18 = circuit_mul(t17, in0);
    let t19 = circuit_mul(t18, in0);
    let t20 = circuit_mul(t19, in0);
    let t21 = circuit_mul(t20, in0);
    let t22 = circuit_mul(t21, in0);
    let t23 = circuit_mul(t22, in0);
    let t24 = circuit_mul(t23, in0);
    let t25 = circuit_mul(t24, in0);
    let t26 = circuit_mul(t25, in0);
    let t27 = circuit_mul(t26, in0);
    let t28 = circuit_mul(t27, in0);
    let t29 = circuit_mul(t28, in0);
    let t30 = circuit_mul(t29, in0);
    let t31 = circuit_mul(t30, in0);
    let t32 = circuit_mul(t31, in0);
    let t33 = circuit_mul(t32, in0);
    let t34 = circuit_mul(t33, in0);
    let t35 = circuit_mul(t34, in0);
    let t36 = circuit_mul(t35, in0);
    let t37 = circuit_mul(t36, in0);
    let t38 = circuit_mul(t37, in0);
    let t39 = circuit_mul(t38, in0);
    let t40 = circuit_mul(t39, in0);
    let t41 = circuit_mul(t40, in0);
    let t42 = circuit_mul(t41, in0);
    let t43 = circuit_mul(t42, in0);
    let t44 = circuit_mul(t43, in0);
    let t45 = circuit_mul(t44, in0);
    let t46 = circuit_mul(t45, in0);
    let t47 = circuit_mul(t46, in0);
    let t48 = circuit_mul(t47, in0);
    let t49 = circuit_mul(t48, in0);
    let t50 = circuit_mul(t49, in0);
    let t51 = circuit_mul(t50, in0);
    let t52 = circuit_mul(t51, in0);
    let t53 = circuit_mul(t52, in0);
    let t54 = circuit_mul(t53, in0);
    let t55 = circuit_mul(t54, in0);
    let t56 = circuit_mul(t55, in0);
    let t57 = circuit_mul(t56, in0);
    let t58 = circuit_mul(t57, in0);
    let t59 = circuit_mul(t58, in0);
    let t60 = circuit_mul(t59, in0);
    let t61 = circuit_mul(t60, in0);
    let t62 = circuit_mul(t61, in0);
    let t63 = circuit_mul(t62, in0);
    let t64 = circuit_mul(t63, in0);
    let t65 = circuit_mul(t64, in0);
    let t66 = circuit_mul(t65, in0);
    let t67 = circuit_mul(t66, in0);
    let t68 = circuit_mul(t67, in0);
    let t69 = circuit_mul(t68, in0);
    let t70 = circuit_mul(t69, in0);
    let t71 = circuit_mul(t70, in0);
    let t72 = circuit_mul(t71, in0);
    let t73 = circuit_mul(t72, in0);
    let t74 = circuit_mul(t73, in0);
    let t75 = circuit_mul(t74, in0);
    let t76 = circuit_mul(t75, in0);
    let t77 = circuit_mul(t76, in0);
    let t78 = circuit_mul(t77, in0);
    let t79 = circuit_mul(t78, in0);
    let t80 = circuit_mul(t79, in0);
    let t81 = circuit_mul(t80, in0);
    let t82 = circuit_mul(t81, in0);
    let t83 = circuit_mul(t82, in0);
    let t84 = circuit_mul(t83, in0);
    let t85 = circuit_mul(t84, in0);
    let t86 = circuit_mul(t85, in0);
    let t87 = circuit_mul(t86, in0);
    let t88 = circuit_mul(t87, in0);
    let t89 = circuit_mul(t88, in0);
    let t90 = circuit_mul(t89, in0);
    let t91 = circuit_mul(t90, in0);
    let t92 = circuit_mul(t91, in0);
    let t93 = circuit_mul(t92, in0);
    let t94 = circuit_mul(t93, in0);
    let t95 = circuit_mul(t94, in0);
    let t96 = circuit_mul(t95, in0);
    let t97 = circuit_mul(t96, in0);
    let t98 = circuit_mul(t97, in0);
    let t99 = circuit_mul(t98, in0);
    let t100 = circuit_mul(t99, in0);
    let t101 = circuit_mul(t100, in0);
    let t102 = circuit_mul(t101, in0);
    let t103 = circuit_mul(t102, in0);
    let t104 = circuit_mul(t103, in0);
    let t105 = circuit_mul(t104, in0);
    let t106 = circuit_mul(t105, in0);
    let t107 = circuit_mul(t106, in0);
    let t108 = circuit_mul(t107, in0);
    let t109 = circuit_mul(t108, in0);
    let t110 = circuit_mul(t109, in0);
    let t111 = circuit_mul(t110, in0);
    let t112 = circuit_mul(t111, in0);
    let t113 = circuit_mul(t112, in0);
    let t114 = circuit_mul(t113, in0);
    let t115 = circuit_mul(t114, in0);
    let t116 = circuit_mul(t115, in0);
    let t117 = circuit_mul(t116, in0);
    let t118 = circuit_mul(t117, in0);
    let t119 = circuit_mul(t118, in0);
    let t120 = circuit_mul(t119, in0);
    let t121 = circuit_mul(t120, in0);
    let t122 = circuit_mul(t121, in0);
    let t123 = circuit_mul(t122, in0);
    let t124 = circuit_mul(t123, in0);
    let t125 = circuit_mul(t124, in0);
    let t126 = circuit_mul(t125, in0);
    let t127 = circuit_mul(t126, in0);
    let t128 = circuit_mul(t127, in0);
    let t129 = circuit_mul(t128, in0);
    let t130 = circuit_mul(t129, in0);
    let t131 = circuit_mul(t130, in0);
    let t132 = circuit_mul(t131, in0);
    let t133 = circuit_mul(t132, in0);
    let t134 = circuit_mul(t133, in0);
    let t135 = circuit_mul(t134, in0);
    let t136 = circuit_mul(t135, in0);
    let t137 = circuit_mul(t136, in0);
    let t138 = circuit_mul(t137, in0);
    let t139 = circuit_mul(t138, in0);
    let t140 = circuit_mul(t139, in0);
    let t141 = circuit_mul(t140, in0);
    let t142 = circuit_mul(t141, in0);
    let t143 = circuit_mul(t142, in0);
    let t144 = circuit_mul(t143, in0);
    let t145 = circuit_mul(t144, in0);
    let t146 = circuit_mul(t145, in0);
    let t147 = circuit_mul(t146, in0);
    let t148 = circuit_mul(t147, in0);
    let t149 = circuit_mul(t148, in0);
    let t150 = circuit_mul(t149, in0);
    let t151 = circuit_mul(t150, in0);
    let t152 = circuit_mul(t151, in0);
    let t153 = circuit_mul(t152, in0);
    let t154 = circuit_mul(t153, in0);
    let t155 = circuit_mul(t154, in0);
    let t156 = circuit_mul(t155, in0);
    let t157 = circuit_mul(t156, in0);
    let t158 = circuit_mul(t157, in0);
    let t159 = circuit_mul(t158, in0);
    let t160 = circuit_mul(t159, in0);
    let t161 = circuit_mul(t160, in0);
    let t162 = circuit_mul(t161, in0);
    let t163 = circuit_mul(t162, in0);
    let t164 = circuit_mul(t163, in0);
    let t165 = circuit_mul(t164, in0);
    let t166 = circuit_mul(t165, in0);
    let t167 = circuit_mul(t166, in0);
    let t168 = circuit_mul(t167, in0);
    let t169 = circuit_mul(t168, in0);
    let t170 = circuit_mul(t169, in0);
    let t171 = circuit_mul(t170, in0);
    let t172 = circuit_mul(t171, in0);
    let t173 = circuit_mul(t172, in0);
    let t174 = circuit_mul(t173, in0);
    let t175 = circuit_mul(t174, in0);
    let t176 = circuit_mul(t175, in0);
    let t177 = circuit_mul(t176, in0);
    let t178 = circuit_mul(t177, in0);
    let t179 = circuit_mul(t178, in0);
    let t180 = circuit_mul(t179, in0);
    let t181 = circuit_mul(t180, in0);
    let t182 = circuit_mul(t181, in0);
    let t183 = circuit_mul(t182, in0);
    let t184 = circuit_mul(t183, in0);
    let t185 = circuit_mul(t184, in0);
    let t186 = circuit_mul(t185, in0);
    let t187 = circuit_mul(t186, in0);
    let t188 = circuit_mul(t187, in0);
    let t189 = circuit_mul(t188, in0);
    let t190 = circuit_mul(t189, in0);
    let t191 = circuit_mul(t190, in0);
    let t192 = circuit_mul(t191, in0);
    let t193 = circuit_mul(t192, in0);
    let t194 = circuit_mul(t193, in0);
    let t195 = circuit_mul(t194, in0);
    let t196 = circuit_mul(t195, in0);
    let t197 = circuit_mul(t196, in0);
    let t198 = circuit_mul(t197, in0);
    let t199 = circuit_mul(t198, in0);
    let t200 = circuit_sub(in8, in1);
    let t201 = circuit_inverse(t200);
    let t202 = circuit_sub(t199, in1);
    let t203 = circuit_inverse(t202);
    let t204 = circuit_mul(in8, in8);
    let t205 = circuit_mul(t204, t204);
    let t206 = circuit_mul(t205, t205);
    let t207 = circuit_mul(t206, t206);
    let t208 = circuit_mul(t207, t207);
    let t209 = circuit_mul(t208, t208);
    let t210 = circuit_mul(t209, t209);
    let t211 = circuit_mul(t210, t210);
    let t212 = circuit_sub(t211, in1);
    let t213 = circuit_mul(t212, in2);
    let t214 = circuit_mul(in9, t213);
    let t215 = circuit_mul(t201, t213);
    let t216 = circuit_mul(t203, t213);
    let t217 = circuit_mul(t215, in6);
    let t218 = circuit_sub(in8, in0);
    let t219 = circuit_sub(in5, in6);
    let t220 = circuit_mul(in4, t214);
    let t221 = circuit_sub(t219, t220);
    let t222 = circuit_mul(t218, t221);
    let t223 = circuit_add(t217, t222);
    let t224 = circuit_sub(in6, in3);
    let t225 = circuit_mul(t216, t224);
    let t226 = circuit_add(t223, t225);
    let t227 = circuit_mul(t212, in7);
    let t228 = circuit_sub(t226, t227);

    let modulus = modulus;

    let mut circuit_inputs = (t212, t228).new_inputs();
    // Prefill constants:
    circuit_inputs = circuit_inputs
        .next_2(
            [0x8712848a692c553d0329f5d6, 0x64751ad938e2b5e6a54cf8c6, 0x204bd3277422fad3, 0x0],
        ); // in0
    circuit_inputs = circuit_inputs.next_2([0x1, 0x0, 0x0, 0x0]); // in1
    circuit_inputs = circuit_inputs
        .next_2(
            [0x313fb720b29e139e5c100001, 0x8e97f570caffd704cb0bb460, 0x3033ea246e506e89, 0x0],
        ); // in2
    // Fill inputs:
    circuit_inputs = circuit_inputs.next_2(p_libra_evaluation); // in3

    for val in p_libra_poly_evals {
        circuit_inputs = circuit_inputs.next_u256(*val);
    } // in4 - in7

    circuit_inputs = circuit_inputs.next_2(tp_gemini_r); // in8
    circuit_inputs = circuit_inputs.next_2(challenge_poly_eval); // in9
    circuit_inputs = circuit_inputs.next_2(root_power_times_tp_gemini_r); // in10

    let outputs = circuit_inputs.done_2().eval(modulus).unwrap();
    let vanishing_check: u384 = outputs.get_output(t212);
    let diff_check: u384 = outputs.get_output(t228);
    return (vanishing_check, diff_check);
}

impl CircuitDefinition46<
    E0,
    E1,
    E2,
    E3,
    E4,
    E5,
    E6,
    E7,
    E8,
    E9,
    E10,
    E11,
    E12,
    E13,
    E14,
    E15,
    E16,
    E17,
    E18,
    E19,
    E20,
    E21,
    E22,
    E23,
    E24,
    E25,
    E26,
    E27,
    E28,
    E29,
    E30,
    E31,
    E32,
    E33,
    E34,
    E35,
    E36,
    E37,
    E38,
    E39,
    E40,
    E41,
    E42,
    E43,
    E44,
    E45,
> of core::circuit::CircuitDefinition<
    (
        CE<E0>,
        CE<E1>,
        CE<E2>,
        CE<E3>,
        CE<E4>,
        CE<E5>,
        CE<E6>,
        CE<E7>,
        CE<E8>,
        CE<E9>,
        CE<E10>,
        CE<E11>,
        CE<E12>,
        CE<E13>,
        CE<E14>,
        CE<E15>,
        CE<E16>,
        CE<E17>,
        CE<E18>,
        CE<E19>,
        CE<E20>,
        CE<E21>,
        CE<E22>,
        CE<E23>,
        CE<E24>,
        CE<E25>,
        CE<E26>,
        CE<E27>,
        CE<E28>,
        CE<E29>,
        CE<E30>,
        CE<E31>,
        CE<E32>,
        CE<E33>,
        CE<E34>,
        CE<E35>,
        CE<E36>,
        CE<E37>,
        CE<E38>,
        CE<E39>,
        CE<E40>,
        CE<E41>,
        CE<E42>,
        CE<E43>,
        CE<E44>,
        CE<E45>,
    ),
> {
    type CircuitType =
        core::circuit::Circuit<
            (
                E0,
                E1,
                E2,
                E3,
                E4,
                E5,
                E6,
                E7,
                E8,
                E9,
                E10,
                E11,
                E12,
                E13,
                E14,
                E15,
                E16,
                E17,
                E18,
                E19,
                E20,
                E21,
                E22,
                E23,
                E24,
                E25,
                E26,
                E27,
                E28,
                E29,
                E30,
                E31,
                E32,
                E33,
                E34,
                E35,
                E36,
                E37,
                E38,
                E39,
                E40,
                E41,
                E42,
                E43,
                E44,
                E45,
            ),
        >;
}
impl MyDrp_46<
    E0,
    E1,
    E2,
    E3,
    E4,
    E5,
    E6,
    E7,
    E8,
    E9,
    E10,
    E11,
    E12,
    E13,
    E14,
    E15,
    E16,
    E17,
    E18,
    E19,
    E20,
    E21,
    E22,
    E23,
    E24,
    E25,
    E26,
    E27,
    E28,
    E29,
    E30,
    E31,
    E32,
    E33,
    E34,
    E35,
    E36,
    E37,
    E38,
    E39,
    E40,
    E41,
    E42,
    E43,
    E44,
    E45,
> of Drop<
    (
        CE<E0>,
        CE<E1>,
        CE<E2>,
        CE<E3>,
        CE<E4>,
        CE<E5>,
        CE<E6>,
        CE<E7>,
        CE<E8>,
        CE<E9>,
        CE<E10>,
        CE<E11>,
        CE<E12>,
        CE<E13>,
        CE<E14>,
        CE<E15>,
        CE<E16>,
        CE<E17>,
        CE<E18>,
        CE<E19>,
        CE<E20>,
        CE<E21>,
        CE<E22>,
        CE<E23>,
        CE<E24>,
        CE<E25>,
        CE<E26>,
        CE<E27>,
        CE<E28>,
        CE<E29>,
        CE<E30>,
        CE<E31>,
        CE<E32>,
        CE<E33>,
        CE<E34>,
        CE<E35>,
        CE<E36>,
        CE<E37>,
        CE<E38>,
        CE<E39>,
        CE<E40>,
        CE<E41>,
        CE<E42>,
        CE<E43>,
        CE<E44>,
        CE<E45>,
    ),
>;

#[inline(never)]
pub fn is_on_curve_excluding_infinity_bn254(p: G1Point, modulus: CircuitModulus) -> bool {
    // INPUT stack
    // y^2 = x^3 + 3
    let (in0, in1) = (CE::<CI<0>> {}, CE::<CI<1>> {});
    let y2 = circuit_mul(in1, in1);
    let x2 = circuit_mul(in0, in0);
    let x3 = circuit_mul(in0, x2);
    let y2_minus_x3 = circuit_sub(y2, x3);

    let mut circuit_inputs = (y2_minus_x3,).new_inputs();
    // Prefill constants:

    // Fill inputs:
    circuit_inputs = circuit_inputs.next_2(p.x); // in0
    circuit_inputs = circuit_inputs.next_2(p.y); // in1

    let outputs = circuit_inputs.done_2().eval(modulus).unwrap();
    let zero_check: u384 = outputs.get_output(y2_minus_x3);
    return zero_check == u384 { limb0: 3, limb1: 0, limb2: 0, limb3: 0 };
}

